// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/applicationschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApplicationSchemaDelete is the builder for deleting a ApplicationSchema entity.
type ApplicationSchemaDelete struct {
	config
	hooks    []Hook
	mutation *ApplicationSchemaMutation
}

// Where appends a list predicates to the ApplicationSchemaDelete builder.
func (asd *ApplicationSchemaDelete) Where(ps ...predicate.ApplicationSchema) *ApplicationSchemaDelete {
	asd.mutation.Where(ps...)
	return asd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (asd *ApplicationSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, asd.sqlExec, asd.mutation, asd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (asd *ApplicationSchemaDelete) ExecX(ctx context.Context) int {
	n, err := asd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (asd *ApplicationSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(applicationschema.Table, sqlgraph.NewFieldSpec(applicationschema.FieldID, field.TypeInt))
	if ps := asd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, asd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	asd.mutation.done = true
	return affected, err
}

// ApplicationSchemaDeleteOne is the builder for deleting a single ApplicationSchema entity.
type ApplicationSchemaDeleteOne struct {
	asd *ApplicationSchemaDelete
}

// Where appends a list predicates to the ApplicationSchemaDelete builder.
func (asdo *ApplicationSchemaDeleteOne) Where(ps ...predicate.ApplicationSchema) *ApplicationSchemaDeleteOne {
	asdo.asd.mutation.Where(ps...)
	return asdo
}

// Exec executes the deletion query.
func (asdo *ApplicationSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := asdo.asd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{applicationschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (asdo *ApplicationSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := asdo.Exec(ctx); err != nil {
		panic(err)
	}
}
