// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"persona/libs/database/ent/applicationschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApplicationSchemaUpdate is the builder for updating ApplicationSchema entities.
type ApplicationSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *ApplicationSchemaMutation
}

// Where appends a list predicates to the ApplicationSchemaUpdate builder.
func (asu *ApplicationSchemaUpdate) Where(ps ...predicate.ApplicationSchema) *ApplicationSchemaUpdate {
	asu.mutation.Where(ps...)
	return asu
}

// Mutation returns the ApplicationSchemaMutation object of the builder.
func (asu *ApplicationSchemaUpdate) Mutation() *ApplicationSchemaMutation {
	return asu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (asu *ApplicationSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, asu.sqlSave, asu.mutation, asu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asu *ApplicationSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := asu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (asu *ApplicationSchemaUpdate) Exec(ctx context.Context) error {
	_, err := asu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asu *ApplicationSchemaUpdate) ExecX(ctx context.Context) {
	if err := asu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (asu *ApplicationSchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(applicationschema.Table, applicationschema.Columns, sqlgraph.NewFieldSpec(applicationschema.FieldID, field.TypeInt))
	if ps := asu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, asu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	asu.mutation.done = true
	return n, nil
}

// ApplicationSchemaUpdateOne is the builder for updating a single ApplicationSchema entity.
type ApplicationSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApplicationSchemaMutation
}

// Mutation returns the ApplicationSchemaMutation object of the builder.
func (asuo *ApplicationSchemaUpdateOne) Mutation() *ApplicationSchemaMutation {
	return asuo.mutation
}

// Where appends a list predicates to the ApplicationSchemaUpdate builder.
func (asuo *ApplicationSchemaUpdateOne) Where(ps ...predicate.ApplicationSchema) *ApplicationSchemaUpdateOne {
	asuo.mutation.Where(ps...)
	return asuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (asuo *ApplicationSchemaUpdateOne) Select(field string, fields ...string) *ApplicationSchemaUpdateOne {
	asuo.fields = append([]string{field}, fields...)
	return asuo
}

// Save executes the query and returns the updated ApplicationSchema entity.
func (asuo *ApplicationSchemaUpdateOne) Save(ctx context.Context) (*ApplicationSchema, error) {
	return withHooks(ctx, asuo.sqlSave, asuo.mutation, asuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asuo *ApplicationSchemaUpdateOne) SaveX(ctx context.Context) *ApplicationSchema {
	node, err := asuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (asuo *ApplicationSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := asuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asuo *ApplicationSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := asuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (asuo *ApplicationSchemaUpdateOne) sqlSave(ctx context.Context) (_node *ApplicationSchema, err error) {
	_spec := sqlgraph.NewUpdateSpec(applicationschema.Table, applicationschema.Columns, sqlgraph.NewFieldSpec(applicationschema.FieldID, field.TypeInt))
	id, ok := asuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApplicationSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := asuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applicationschema.FieldID)
		for _, f := range fields {
			if !applicationschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != applicationschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := asuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ApplicationSchema{config: asuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, asuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{applicationschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	asuo.mutation.done = true
	return _node, nil
}
