// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/assignmentschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssignmentSchemaQuery is the builder for querying AssignmentSchema entities.
type AssignmentSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []assignmentschema.OrderOption
	inters     []Interceptor
	predicates []predicate.AssignmentSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AssignmentSchemaQuery builder.
func (asq *AssignmentSchemaQuery) Where(ps ...predicate.AssignmentSchema) *AssignmentSchemaQuery {
	asq.predicates = append(asq.predicates, ps...)
	return asq
}

// Limit the number of records to be returned by this query.
func (asq *AssignmentSchemaQuery) Limit(limit int) *AssignmentSchemaQuery {
	asq.ctx.Limit = &limit
	return asq
}

// Offset to start from.
func (asq *AssignmentSchemaQuery) Offset(offset int) *AssignmentSchemaQuery {
	asq.ctx.Offset = &offset
	return asq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (asq *AssignmentSchemaQuery) Unique(unique bool) *AssignmentSchemaQuery {
	asq.ctx.Unique = &unique
	return asq
}

// Order specifies how the records should be ordered.
func (asq *AssignmentSchemaQuery) Order(o ...assignmentschema.OrderOption) *AssignmentSchemaQuery {
	asq.order = append(asq.order, o...)
	return asq
}

// First returns the first AssignmentSchema entity from the query.
// Returns a *NotFoundError when no AssignmentSchema was found.
func (asq *AssignmentSchemaQuery) First(ctx context.Context) (*AssignmentSchema, error) {
	nodes, err := asq.Limit(1).All(setContextOp(ctx, asq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{assignmentschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) FirstX(ctx context.Context) *AssignmentSchema {
	node, err := asq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AssignmentSchema ID from the query.
// Returns a *NotFoundError when no AssignmentSchema ID was found.
func (asq *AssignmentSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(1).IDs(setContextOp(ctx, asq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{assignmentschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := asq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AssignmentSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AssignmentSchema entity is found.
// Returns a *NotFoundError when no AssignmentSchema entities are found.
func (asq *AssignmentSchemaQuery) Only(ctx context.Context) (*AssignmentSchema, error) {
	nodes, err := asq.Limit(2).All(setContextOp(ctx, asq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{assignmentschema.Label}
	default:
		return nil, &NotSingularError{assignmentschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) OnlyX(ctx context.Context) *AssignmentSchema {
	node, err := asq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AssignmentSchema ID in the query.
// Returns a *NotSingularError when more than one AssignmentSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (asq *AssignmentSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(2).IDs(setContextOp(ctx, asq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{assignmentschema.Label}
	default:
		err = &NotSingularError{assignmentschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := asq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AssignmentSchemas.
func (asq *AssignmentSchemaQuery) All(ctx context.Context) ([]*AssignmentSchema, error) {
	ctx = setContextOp(ctx, asq.ctx, "All")
	if err := asq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AssignmentSchema, *AssignmentSchemaQuery]()
	return withInterceptors[[]*AssignmentSchema](ctx, asq, qr, asq.inters)
}

// AllX is like All, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) AllX(ctx context.Context) []*AssignmentSchema {
	nodes, err := asq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AssignmentSchema IDs.
func (asq *AssignmentSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if asq.ctx.Unique == nil && asq.path != nil {
		asq.Unique(true)
	}
	ctx = setContextOp(ctx, asq.ctx, "IDs")
	if err = asq.Select(assignmentschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := asq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (asq *AssignmentSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, asq.ctx, "Count")
	if err := asq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, asq, querierCount[*AssignmentSchemaQuery](), asq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) CountX(ctx context.Context) int {
	count, err := asq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (asq *AssignmentSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, asq.ctx, "Exist")
	switch _, err := asq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (asq *AssignmentSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := asq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AssignmentSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (asq *AssignmentSchemaQuery) Clone() *AssignmentSchemaQuery {
	if asq == nil {
		return nil
	}
	return &AssignmentSchemaQuery{
		config:     asq.config,
		ctx:        asq.ctx.Clone(),
		order:      append([]assignmentschema.OrderOption{}, asq.order...),
		inters:     append([]Interceptor{}, asq.inters...),
		predicates: append([]predicate.AssignmentSchema{}, asq.predicates...),
		// clone intermediate query.
		sql:  asq.sql.Clone(),
		path: asq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AssignmentSchema.Query().
//		GroupBy(assignmentschema.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (asq *AssignmentSchemaQuery) GroupBy(field string, fields ...string) *AssignmentSchemaGroupBy {
	asq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AssignmentSchemaGroupBy{build: asq}
	grbuild.flds = &asq.ctx.Fields
	grbuild.label = assignmentschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AssignmentSchema.Query().
//		Select(assignmentschema.FieldName).
//		Scan(ctx, &v)
func (asq *AssignmentSchemaQuery) Select(fields ...string) *AssignmentSchemaSelect {
	asq.ctx.Fields = append(asq.ctx.Fields, fields...)
	sbuild := &AssignmentSchemaSelect{AssignmentSchemaQuery: asq}
	sbuild.label = assignmentschema.Label
	sbuild.flds, sbuild.scan = &asq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AssignmentSchemaSelect configured with the given aggregations.
func (asq *AssignmentSchemaQuery) Aggregate(fns ...AggregateFunc) *AssignmentSchemaSelect {
	return asq.Select().Aggregate(fns...)
}

func (asq *AssignmentSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range asq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, asq); err != nil {
				return err
			}
		}
	}
	for _, f := range asq.ctx.Fields {
		if !assignmentschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if asq.path != nil {
		prev, err := asq.path(ctx)
		if err != nil {
			return err
		}
		asq.sql = prev
	}
	return nil
}

func (asq *AssignmentSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AssignmentSchema, error) {
	var (
		nodes = []*AssignmentSchema{}
		_spec = asq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AssignmentSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AssignmentSchema{config: asq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, asq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (asq *AssignmentSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := asq.querySpec()
	_spec.Node.Columns = asq.ctx.Fields
	if len(asq.ctx.Fields) > 0 {
		_spec.Unique = asq.ctx.Unique != nil && *asq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, asq.driver, _spec)
}

func (asq *AssignmentSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(assignmentschema.Table, assignmentschema.Columns, sqlgraph.NewFieldSpec(assignmentschema.FieldID, field.TypeInt))
	_spec.From = asq.sql
	if unique := asq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if asq.path != nil {
		_spec.Unique = true
	}
	if fields := asq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assignmentschema.FieldID)
		for i := range fields {
			if fields[i] != assignmentschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := asq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := asq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := asq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := asq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (asq *AssignmentSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(asq.driver.Dialect())
	t1 := builder.Table(assignmentschema.Table)
	columns := asq.ctx.Fields
	if len(columns) == 0 {
		columns = assignmentschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if asq.sql != nil {
		selector = asq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if asq.ctx.Unique != nil && *asq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range asq.predicates {
		p(selector)
	}
	for _, p := range asq.order {
		p(selector)
	}
	if offset := asq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := asq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AssignmentSchemaGroupBy is the group-by builder for AssignmentSchema entities.
type AssignmentSchemaGroupBy struct {
	selector
	build *AssignmentSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (asgb *AssignmentSchemaGroupBy) Aggregate(fns ...AggregateFunc) *AssignmentSchemaGroupBy {
	asgb.fns = append(asgb.fns, fns...)
	return asgb
}

// Scan applies the selector query and scans the result into the given value.
func (asgb *AssignmentSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, asgb.build.ctx, "GroupBy")
	if err := asgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssignmentSchemaQuery, *AssignmentSchemaGroupBy](ctx, asgb.build, asgb, asgb.build.inters, v)
}

func (asgb *AssignmentSchemaGroupBy) sqlScan(ctx context.Context, root *AssignmentSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(asgb.fns))
	for _, fn := range asgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*asgb.flds)+len(asgb.fns))
		for _, f := range *asgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*asgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := asgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AssignmentSchemaSelect is the builder for selecting fields of AssignmentSchema entities.
type AssignmentSchemaSelect struct {
	*AssignmentSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ass *AssignmentSchemaSelect) Aggregate(fns ...AggregateFunc) *AssignmentSchemaSelect {
	ass.fns = append(ass.fns, fns...)
	return ass
}

// Scan applies the selector query and scans the result into the given value.
func (ass *AssignmentSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ass.ctx, "Select")
	if err := ass.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AssignmentSchemaQuery, *AssignmentSchemaSelect](ctx, ass.AssignmentSchemaQuery, ass, ass.inters, v)
}

func (ass *AssignmentSchemaSelect) sqlScan(ctx context.Context, root *AssignmentSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ass.fns))
	for _, fn := range ass.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ass.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
