// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"persona/libs/database/ent/assignmentschema"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssignmentSchemaCreate is the builder for creating a AssignmentSchema entity.
type AssignmentSchemaCreate struct {
	config
	mutation *AssignmentSchemaMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (asc *AssignmentSchemaCreate) SetName(s string) *AssignmentSchemaCreate {
	asc.mutation.SetName(s)
	return asc
}

// SetType sets the "type" field.
func (asc *AssignmentSchemaCreate) SetType(s string) *AssignmentSchemaCreate {
	asc.mutation.SetType(s)
	return asc
}

// Mutation returns the AssignmentSchemaMutation object of the builder.
func (asc *AssignmentSchemaCreate) Mutation() *AssignmentSchemaMutation {
	return asc.mutation
}

// Save creates the AssignmentSchema in the database.
func (asc *AssignmentSchemaCreate) Save(ctx context.Context) (*AssignmentSchema, error) {
	return withHooks(ctx, asc.sqlSave, asc.mutation, asc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (asc *AssignmentSchemaCreate) SaveX(ctx context.Context) *AssignmentSchema {
	v, err := asc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (asc *AssignmentSchemaCreate) Exec(ctx context.Context) error {
	_, err := asc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asc *AssignmentSchemaCreate) ExecX(ctx context.Context) {
	if err := asc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asc *AssignmentSchemaCreate) check() error {
	if _, ok := asc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AssignmentSchema.name"`)}
	}
	if _, ok := asc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "AssignmentSchema.type"`)}
	}
	return nil
}

func (asc *AssignmentSchemaCreate) sqlSave(ctx context.Context) (*AssignmentSchema, error) {
	if err := asc.check(); err != nil {
		return nil, err
	}
	_node, _spec := asc.createSpec()
	if err := sqlgraph.CreateNode(ctx, asc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	asc.mutation.id = &_node.ID
	asc.mutation.done = true
	return _node, nil
}

func (asc *AssignmentSchemaCreate) createSpec() (*AssignmentSchema, *sqlgraph.CreateSpec) {
	var (
		_node = &AssignmentSchema{config: asc.config}
		_spec = sqlgraph.NewCreateSpec(assignmentschema.Table, sqlgraph.NewFieldSpec(assignmentschema.FieldID, field.TypeInt))
	)
	if value, ok := asc.mutation.Name(); ok {
		_spec.SetField(assignmentschema.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := asc.mutation.GetType(); ok {
		_spec.SetField(assignmentschema.FieldType, field.TypeString, value)
		_node.Type = value
	}
	return _node, _spec
}

// AssignmentSchemaCreateBulk is the builder for creating many AssignmentSchema entities in bulk.
type AssignmentSchemaCreateBulk struct {
	config
	builders []*AssignmentSchemaCreate
}

// Save creates the AssignmentSchema entities in the database.
func (ascb *AssignmentSchemaCreateBulk) Save(ctx context.Context) ([]*AssignmentSchema, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ascb.builders))
	nodes := make([]*AssignmentSchema, len(ascb.builders))
	mutators := make([]Mutator, len(ascb.builders))
	for i := range ascb.builders {
		func(i int, root context.Context) {
			builder := ascb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssignmentSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ascb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ascb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ascb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ascb *AssignmentSchemaCreateBulk) SaveX(ctx context.Context) []*AssignmentSchema {
	v, err := ascb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ascb *AssignmentSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := ascb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ascb *AssignmentSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := ascb.Exec(ctx); err != nil {
		panic(err)
	}
}
