// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"persona/libs/database/ent/assignmentschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssignmentSchemaUpdate is the builder for updating AssignmentSchema entities.
type AssignmentSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *AssignmentSchemaMutation
}

// Where appends a list predicates to the AssignmentSchemaUpdate builder.
func (asu *AssignmentSchemaUpdate) Where(ps ...predicate.AssignmentSchema) *AssignmentSchemaUpdate {
	asu.mutation.Where(ps...)
	return asu
}

// SetName sets the "name" field.
func (asu *AssignmentSchemaUpdate) SetName(s string) *AssignmentSchemaUpdate {
	asu.mutation.SetName(s)
	return asu
}

// SetType sets the "type" field.
func (asu *AssignmentSchemaUpdate) SetType(s string) *AssignmentSchemaUpdate {
	asu.mutation.SetType(s)
	return asu
}

// Mutation returns the AssignmentSchemaMutation object of the builder.
func (asu *AssignmentSchemaUpdate) Mutation() *AssignmentSchemaMutation {
	return asu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (asu *AssignmentSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, asu.sqlSave, asu.mutation, asu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asu *AssignmentSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := asu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (asu *AssignmentSchemaUpdate) Exec(ctx context.Context) error {
	_, err := asu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asu *AssignmentSchemaUpdate) ExecX(ctx context.Context) {
	if err := asu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (asu *AssignmentSchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(assignmentschema.Table, assignmentschema.Columns, sqlgraph.NewFieldSpec(assignmentschema.FieldID, field.TypeInt))
	if ps := asu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asu.mutation.Name(); ok {
		_spec.SetField(assignmentschema.FieldName, field.TypeString, value)
	}
	if value, ok := asu.mutation.GetType(); ok {
		_spec.SetField(assignmentschema.FieldType, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, asu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmentschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	asu.mutation.done = true
	return n, nil
}

// AssignmentSchemaUpdateOne is the builder for updating a single AssignmentSchema entity.
type AssignmentSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssignmentSchemaMutation
}

// SetName sets the "name" field.
func (asuo *AssignmentSchemaUpdateOne) SetName(s string) *AssignmentSchemaUpdateOne {
	asuo.mutation.SetName(s)
	return asuo
}

// SetType sets the "type" field.
func (asuo *AssignmentSchemaUpdateOne) SetType(s string) *AssignmentSchemaUpdateOne {
	asuo.mutation.SetType(s)
	return asuo
}

// Mutation returns the AssignmentSchemaMutation object of the builder.
func (asuo *AssignmentSchemaUpdateOne) Mutation() *AssignmentSchemaMutation {
	return asuo.mutation
}

// Where appends a list predicates to the AssignmentSchemaUpdate builder.
func (asuo *AssignmentSchemaUpdateOne) Where(ps ...predicate.AssignmentSchema) *AssignmentSchemaUpdateOne {
	asuo.mutation.Where(ps...)
	return asuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (asuo *AssignmentSchemaUpdateOne) Select(field string, fields ...string) *AssignmentSchemaUpdateOne {
	asuo.fields = append([]string{field}, fields...)
	return asuo
}

// Save executes the query and returns the updated AssignmentSchema entity.
func (asuo *AssignmentSchemaUpdateOne) Save(ctx context.Context) (*AssignmentSchema, error) {
	return withHooks(ctx, asuo.sqlSave, asuo.mutation, asuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (asuo *AssignmentSchemaUpdateOne) SaveX(ctx context.Context) *AssignmentSchema {
	node, err := asuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (asuo *AssignmentSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := asuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asuo *AssignmentSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := asuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (asuo *AssignmentSchemaUpdateOne) sqlSave(ctx context.Context) (_node *AssignmentSchema, err error) {
	_spec := sqlgraph.NewUpdateSpec(assignmentschema.Table, assignmentschema.Columns, sqlgraph.NewFieldSpec(assignmentschema.FieldID, field.TypeInt))
	id, ok := asuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AssignmentSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := asuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assignmentschema.FieldID)
		for _, f := range fields {
			if !assignmentschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assignmentschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := asuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asuo.mutation.Name(); ok {
		_spec.SetField(assignmentschema.FieldName, field.TypeString, value)
	}
	if value, ok := asuo.mutation.GetType(); ok {
		_spec.SetField(assignmentschema.FieldType, field.TypeString, value)
	}
	_node = &AssignmentSchema{config: asuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, asuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmentschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	asuo.mutation.done = true
	return _node, nil
}
