// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/assignmentschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AssignmentSchemaDelete is the builder for deleting a AssignmentSchema entity.
type AssignmentSchemaDelete struct {
	config
	hooks    []Hook
	mutation *AssignmentSchemaMutation
}

// Where appends a list predicates to the AssignmentSchemaDelete builder.
func (asd *AssignmentSchemaDelete) Where(ps ...predicate.AssignmentSchema) *AssignmentSchemaDelete {
	asd.mutation.Where(ps...)
	return asd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (asd *AssignmentSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, asd.sqlExec, asd.mutation, asd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (asd *AssignmentSchemaDelete) ExecX(ctx context.Context) int {
	n, err := asd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (asd *AssignmentSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(assignmentschema.Table, sqlgraph.NewFieldSpec(assignmentschema.FieldID, field.TypeInt))
	if ps := asd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, asd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	asd.mutation.done = true
	return affected, err
}

// AssignmentSchemaDeleteOne is the builder for deleting a single AssignmentSchema entity.
type AssignmentSchemaDeleteOne struct {
	asd *AssignmentSchemaDelete
}

// Where appends a list predicates to the AssignmentSchemaDelete builder.
func (asdo *AssignmentSchemaDeleteOne) Where(ps ...predicate.AssignmentSchema) *AssignmentSchemaDeleteOne {
	asdo.asd.mutation.Where(ps...)
	return asdo
}

// Exec executes the deletion query.
func (asdo *AssignmentSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := asdo.asd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{assignmentschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (asdo *AssignmentSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := asdo.Exec(ctx); err != nil {
		panic(err)
	}
}
