// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/commentschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentSchemaQuery is the builder for querying CommentSchema entities.
type CommentSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []commentschema.OrderOption
	inters     []Interceptor
	predicates []predicate.CommentSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommentSchemaQuery builder.
func (csq *CommentSchemaQuery) Where(ps ...predicate.CommentSchema) *CommentSchemaQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *CommentSchemaQuery) Limit(limit int) *CommentSchemaQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *CommentSchemaQuery) Offset(offset int) *CommentSchemaQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *CommentSchemaQuery) Unique(unique bool) *CommentSchemaQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *CommentSchemaQuery) Order(o ...commentschema.OrderOption) *CommentSchemaQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// First returns the first CommentSchema entity from the query.
// Returns a *NotFoundError when no CommentSchema was found.
func (csq *CommentSchemaQuery) First(ctx context.Context) (*CommentSchema, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commentschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *CommentSchemaQuery) FirstX(ctx context.Context) *CommentSchema {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommentSchema ID from the query.
// Returns a *NotFoundError when no CommentSchema ID was found.
func (csq *CommentSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commentschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *CommentSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommentSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommentSchema entity is found.
// Returns a *NotFoundError when no CommentSchema entities are found.
func (csq *CommentSchemaQuery) Only(ctx context.Context) (*CommentSchema, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commentschema.Label}
	default:
		return nil, &NotSingularError{commentschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *CommentSchemaQuery) OnlyX(ctx context.Context) *CommentSchema {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommentSchema ID in the query.
// Returns a *NotSingularError when more than one CommentSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *CommentSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commentschema.Label}
	default:
		err = &NotSingularError{commentschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *CommentSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommentSchemas.
func (csq *CommentSchemaQuery) All(ctx context.Context) ([]*CommentSchema, error) {
	ctx = setContextOp(ctx, csq.ctx, "All")
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommentSchema, *CommentSchemaQuery]()
	return withInterceptors[[]*CommentSchema](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *CommentSchemaQuery) AllX(ctx context.Context) []*CommentSchema {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommentSchema IDs.
func (csq *CommentSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, "IDs")
	if err = csq.Select(commentschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *CommentSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *CommentSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, "Count")
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*CommentSchemaQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *CommentSchemaQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *CommentSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, "Exist")
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *CommentSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommentSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *CommentSchemaQuery) Clone() *CommentSchemaQuery {
	if csq == nil {
		return nil
	}
	return &CommentSchemaQuery{
		config:     csq.config,
		ctx:        csq.ctx.Clone(),
		order:      append([]commentschema.OrderOption{}, csq.order...),
		inters:     append([]Interceptor{}, csq.inters...),
		predicates: append([]predicate.CommentSchema{}, csq.predicates...),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (csq *CommentSchemaQuery) GroupBy(field string, fields ...string) *CommentSchemaGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommentSchemaGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = commentschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (csq *CommentSchemaQuery) Select(fields ...string) *CommentSchemaSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &CommentSchemaSelect{CommentSchemaQuery: csq}
	sbuild.label = commentschema.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommentSchemaSelect configured with the given aggregations.
func (csq *CommentSchemaQuery) Aggregate(fns ...AggregateFunc) *CommentSchemaSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *CommentSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !commentschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *CommentSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommentSchema, error) {
	var (
		nodes = []*CommentSchema{}
		_spec = csq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommentSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommentSchema{config: csq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (csq *CommentSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *CommentSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commentschema.Table, commentschema.Columns, sqlgraph.NewFieldSpec(commentschema.FieldID, field.TypeInt))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commentschema.FieldID)
		for i := range fields {
			if fields[i] != commentschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *CommentSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(commentschema.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = commentschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CommentSchemaGroupBy is the group-by builder for CommentSchema entities.
type CommentSchemaGroupBy struct {
	selector
	build *CommentSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *CommentSchemaGroupBy) Aggregate(fns ...AggregateFunc) *CommentSchemaGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *CommentSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, "GroupBy")
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommentSchemaQuery, *CommentSchemaGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *CommentSchemaGroupBy) sqlScan(ctx context.Context, root *CommentSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommentSchemaSelect is the builder for selecting fields of CommentSchema entities.
type CommentSchemaSelect struct {
	*CommentSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *CommentSchemaSelect) Aggregate(fns ...AggregateFunc) *CommentSchemaSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *CommentSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, "Select")
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommentSchemaQuery, *CommentSchemaSelect](ctx, css.CommentSchemaQuery, css, css.inters, v)
}

func (css *CommentSchemaSelect) sqlScan(ctx context.Context, root *CommentSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
