// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"persona/libs/database/ent/coverletterschema"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CoverLetterSchema is the model entity for the CoverLetterSchema schema.
type CoverLetterSchema struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoverLetterSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case coverletterschema.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoverLetterSchema fields.
func (cls *CoverLetterSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coverletterschema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cls.ID = int(value.Int64)
		default:
			cls.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CoverLetterSchema.
// This includes values selected through modifiers, order, etc.
func (cls *CoverLetterSchema) Value(name string) (ent.Value, error) {
	return cls.selectValues.Get(name)
}

// Update returns a builder for updating this CoverLetterSchema.
// Note that you need to call CoverLetterSchema.Unwrap() before calling this method if this CoverLetterSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (cls *CoverLetterSchema) Update() *CoverLetterSchemaUpdateOne {
	return NewCoverLetterSchemaClient(cls.config).UpdateOne(cls)
}

// Unwrap unwraps the CoverLetterSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cls *CoverLetterSchema) Unwrap() *CoverLetterSchema {
	_tx, ok := cls.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoverLetterSchema is not a transactional entity")
	}
	cls.config.driver = _tx.drv
	return cls
}

// String implements the fmt.Stringer.
func (cls *CoverLetterSchema) String() string {
	var builder strings.Builder
	builder.WriteString("CoverLetterSchema(")
	builder.WriteString(fmt.Sprintf("id=%v", cls.ID))
	builder.WriteByte(')')
	return builder.String()
}

// CoverLetterSchemas is a parsable slice of CoverLetterSchema.
type CoverLetterSchemas []*CoverLetterSchema
