// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/coverletterschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CoverLetterSchemaDelete is the builder for deleting a CoverLetterSchema entity.
type CoverLetterSchemaDelete struct {
	config
	hooks    []Hook
	mutation *CoverLetterSchemaMutation
}

// Where appends a list predicates to the CoverLetterSchemaDelete builder.
func (clsd *CoverLetterSchemaDelete) Where(ps ...predicate.CoverLetterSchema) *CoverLetterSchemaDelete {
	clsd.mutation.Where(ps...)
	return clsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (clsd *CoverLetterSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, clsd.sqlExec, clsd.mutation, clsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (clsd *CoverLetterSchemaDelete) ExecX(ctx context.Context) int {
	n, err := clsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (clsd *CoverLetterSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(coverletterschema.Table, sqlgraph.NewFieldSpec(coverletterschema.FieldID, field.TypeInt))
	if ps := clsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, clsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	clsd.mutation.done = true
	return affected, err
}

// CoverLetterSchemaDeleteOne is the builder for deleting a single CoverLetterSchema entity.
type CoverLetterSchemaDeleteOne struct {
	clsd *CoverLetterSchemaDelete
}

// Where appends a list predicates to the CoverLetterSchemaDelete builder.
func (clsdo *CoverLetterSchemaDeleteOne) Where(ps ...predicate.CoverLetterSchema) *CoverLetterSchemaDeleteOne {
	clsdo.clsd.mutation.Where(ps...)
	return clsdo
}

// Exec executes the deletion query.
func (clsdo *CoverLetterSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := clsdo.clsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coverletterschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (clsdo *CoverLetterSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := clsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
