// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/followschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FollowSchemaQuery is the builder for querying FollowSchema entities.
type FollowSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []followschema.OrderOption
	inters     []Interceptor
	predicates []predicate.FollowSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FollowSchemaQuery builder.
func (fsq *FollowSchemaQuery) Where(ps ...predicate.FollowSchema) *FollowSchemaQuery {
	fsq.predicates = append(fsq.predicates, ps...)
	return fsq
}

// Limit the number of records to be returned by this query.
func (fsq *FollowSchemaQuery) Limit(limit int) *FollowSchemaQuery {
	fsq.ctx.Limit = &limit
	return fsq
}

// Offset to start from.
func (fsq *FollowSchemaQuery) Offset(offset int) *FollowSchemaQuery {
	fsq.ctx.Offset = &offset
	return fsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fsq *FollowSchemaQuery) Unique(unique bool) *FollowSchemaQuery {
	fsq.ctx.Unique = &unique
	return fsq
}

// Order specifies how the records should be ordered.
func (fsq *FollowSchemaQuery) Order(o ...followschema.OrderOption) *FollowSchemaQuery {
	fsq.order = append(fsq.order, o...)
	return fsq
}

// First returns the first FollowSchema entity from the query.
// Returns a *NotFoundError when no FollowSchema was found.
func (fsq *FollowSchemaQuery) First(ctx context.Context) (*FollowSchema, error) {
	nodes, err := fsq.Limit(1).All(setContextOp(ctx, fsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{followschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fsq *FollowSchemaQuery) FirstX(ctx context.Context) *FollowSchema {
	node, err := fsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FollowSchema ID from the query.
// Returns a *NotFoundError when no FollowSchema ID was found.
func (fsq *FollowSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(1).IDs(setContextOp(ctx, fsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{followschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fsq *FollowSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := fsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FollowSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FollowSchema entity is found.
// Returns a *NotFoundError when no FollowSchema entities are found.
func (fsq *FollowSchemaQuery) Only(ctx context.Context) (*FollowSchema, error) {
	nodes, err := fsq.Limit(2).All(setContextOp(ctx, fsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{followschema.Label}
	default:
		return nil, &NotSingularError{followschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fsq *FollowSchemaQuery) OnlyX(ctx context.Context) *FollowSchema {
	node, err := fsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FollowSchema ID in the query.
// Returns a *NotSingularError when more than one FollowSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (fsq *FollowSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsq.Limit(2).IDs(setContextOp(ctx, fsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{followschema.Label}
	default:
		err = &NotSingularError{followschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fsq *FollowSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := fsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FollowSchemas.
func (fsq *FollowSchemaQuery) All(ctx context.Context) ([]*FollowSchema, error) {
	ctx = setContextOp(ctx, fsq.ctx, "All")
	if err := fsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FollowSchema, *FollowSchemaQuery]()
	return withInterceptors[[]*FollowSchema](ctx, fsq, qr, fsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fsq *FollowSchemaQuery) AllX(ctx context.Context) []*FollowSchema {
	nodes, err := fsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FollowSchema IDs.
func (fsq *FollowSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fsq.ctx.Unique == nil && fsq.path != nil {
		fsq.Unique(true)
	}
	ctx = setContextOp(ctx, fsq.ctx, "IDs")
	if err = fsq.Select(followschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fsq *FollowSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := fsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fsq *FollowSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Count")
	if err := fsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fsq, querierCount[*FollowSchemaQuery](), fsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fsq *FollowSchemaQuery) CountX(ctx context.Context) int {
	count, err := fsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fsq *FollowSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fsq.ctx, "Exist")
	switch _, err := fsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fsq *FollowSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := fsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FollowSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fsq *FollowSchemaQuery) Clone() *FollowSchemaQuery {
	if fsq == nil {
		return nil
	}
	return &FollowSchemaQuery{
		config:     fsq.config,
		ctx:        fsq.ctx.Clone(),
		order:      append([]followschema.OrderOption{}, fsq.order...),
		inters:     append([]Interceptor{}, fsq.inters...),
		predicates: append([]predicate.FollowSchema{}, fsq.predicates...),
		// clone intermediate query.
		sql:  fsq.sql.Clone(),
		path: fsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (fsq *FollowSchemaQuery) GroupBy(field string, fields ...string) *FollowSchemaGroupBy {
	fsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FollowSchemaGroupBy{build: fsq}
	grbuild.flds = &fsq.ctx.Fields
	grbuild.label = followschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (fsq *FollowSchemaQuery) Select(fields ...string) *FollowSchemaSelect {
	fsq.ctx.Fields = append(fsq.ctx.Fields, fields...)
	sbuild := &FollowSchemaSelect{FollowSchemaQuery: fsq}
	sbuild.label = followschema.Label
	sbuild.flds, sbuild.scan = &fsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FollowSchemaSelect configured with the given aggregations.
func (fsq *FollowSchemaQuery) Aggregate(fns ...AggregateFunc) *FollowSchemaSelect {
	return fsq.Select().Aggregate(fns...)
}

func (fsq *FollowSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fsq); err != nil {
				return err
			}
		}
	}
	for _, f := range fsq.ctx.Fields {
		if !followschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fsq.path != nil {
		prev, err := fsq.path(ctx)
		if err != nil {
			return err
		}
		fsq.sql = prev
	}
	return nil
}

func (fsq *FollowSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FollowSchema, error) {
	var (
		nodes = []*FollowSchema{}
		_spec = fsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FollowSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FollowSchema{config: fsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (fsq *FollowSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fsq.querySpec()
	_spec.Node.Columns = fsq.ctx.Fields
	if len(fsq.ctx.Fields) > 0 {
		_spec.Unique = fsq.ctx.Unique != nil && *fsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fsq.driver, _spec)
}

func (fsq *FollowSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(followschema.Table, followschema.Columns, sqlgraph.NewFieldSpec(followschema.FieldID, field.TypeInt))
	_spec.From = fsq.sql
	if unique := fsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fsq.path != nil {
		_spec.Unique = true
	}
	if fields := fsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, followschema.FieldID)
		for i := range fields {
			if fields[i] != followschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fsq *FollowSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fsq.driver.Dialect())
	t1 := builder.Table(followschema.Table)
	columns := fsq.ctx.Fields
	if len(columns) == 0 {
		columns = followschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fsq.sql != nil {
		selector = fsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fsq.ctx.Unique != nil && *fsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fsq.predicates {
		p(selector)
	}
	for _, p := range fsq.order {
		p(selector)
	}
	if offset := fsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FollowSchemaGroupBy is the group-by builder for FollowSchema entities.
type FollowSchemaGroupBy struct {
	selector
	build *FollowSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fsgb *FollowSchemaGroupBy) Aggregate(fns ...AggregateFunc) *FollowSchemaGroupBy {
	fsgb.fns = append(fsgb.fns, fns...)
	return fsgb
}

// Scan applies the selector query and scans the result into the given value.
func (fsgb *FollowSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fsgb.build.ctx, "GroupBy")
	if err := fsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowSchemaQuery, *FollowSchemaGroupBy](ctx, fsgb.build, fsgb, fsgb.build.inters, v)
}

func (fsgb *FollowSchemaGroupBy) sqlScan(ctx context.Context, root *FollowSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fsgb.fns))
	for _, fn := range fsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fsgb.flds)+len(fsgb.fns))
		for _, f := range *fsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FollowSchemaSelect is the builder for selecting fields of FollowSchema entities.
type FollowSchemaSelect struct {
	*FollowSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fss *FollowSchemaSelect) Aggregate(fns ...AggregateFunc) *FollowSchemaSelect {
	fss.fns = append(fss.fns, fns...)
	return fss
}

// Scan applies the selector query and scans the result into the given value.
func (fss *FollowSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fss.ctx, "Select")
	if err := fss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FollowSchemaQuery, *FollowSchemaSelect](ctx, fss.FollowSchemaQuery, fss, fss.inters, v)
}

func (fss *FollowSchemaSelect) sqlScan(ctx context.Context, root *FollowSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fss.fns))
	for _, fn := range fss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
