// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"persona/libs/database/ent/followschema"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FollowSchema is the model entity for the FollowSchema schema.
type FollowSchema struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FollowSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case followschema.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FollowSchema fields.
func (fs *FollowSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case followschema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			fs.ID = int(value.Int64)
		default:
			fs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FollowSchema.
// This includes values selected through modifiers, order, etc.
func (fs *FollowSchema) Value(name string) (ent.Value, error) {
	return fs.selectValues.Get(name)
}

// Update returns a builder for updating this FollowSchema.
// Note that you need to call FollowSchema.Unwrap() before calling this method if this FollowSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (fs *FollowSchema) Update() *FollowSchemaUpdateOne {
	return NewFollowSchemaClient(fs.config).UpdateOne(fs)
}

// Unwrap unwraps the FollowSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fs *FollowSchema) Unwrap() *FollowSchema {
	_tx, ok := fs.config.driver.(*txDriver)
	if !ok {
		panic("ent: FollowSchema is not a transactional entity")
	}
	fs.config.driver = _tx.drv
	return fs
}

// String implements the fmt.Stringer.
func (fs *FollowSchema) String() string {
	var builder strings.Builder
	builder.WriteString("FollowSchema(")
	builder.WriteString(fmt.Sprintf("id=%v", fs.ID))
	builder.WriteByte(')')
	return builder.String()
}

// FollowSchemas is a parsable slice of FollowSchema.
type FollowSchemas []*FollowSchema
