// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/jobschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobSchemaQuery is the builder for querying JobSchema entities.
type JobSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []jobschema.OrderOption
	inters     []Interceptor
	predicates []predicate.JobSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobSchemaQuery builder.
func (jsq *JobSchemaQuery) Where(ps ...predicate.JobSchema) *JobSchemaQuery {
	jsq.predicates = append(jsq.predicates, ps...)
	return jsq
}

// Limit the number of records to be returned by this query.
func (jsq *JobSchemaQuery) Limit(limit int) *JobSchemaQuery {
	jsq.ctx.Limit = &limit
	return jsq
}

// Offset to start from.
func (jsq *JobSchemaQuery) Offset(offset int) *JobSchemaQuery {
	jsq.ctx.Offset = &offset
	return jsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jsq *JobSchemaQuery) Unique(unique bool) *JobSchemaQuery {
	jsq.ctx.Unique = &unique
	return jsq
}

// Order specifies how the records should be ordered.
func (jsq *JobSchemaQuery) Order(o ...jobschema.OrderOption) *JobSchemaQuery {
	jsq.order = append(jsq.order, o...)
	return jsq
}

// First returns the first JobSchema entity from the query.
// Returns a *NotFoundError when no JobSchema was found.
func (jsq *JobSchemaQuery) First(ctx context.Context) (*JobSchema, error) {
	nodes, err := jsq.Limit(1).All(setContextOp(ctx, jsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jsq *JobSchemaQuery) FirstX(ctx context.Context) *JobSchema {
	node, err := jsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobSchema ID from the query.
// Returns a *NotFoundError when no JobSchema ID was found.
func (jsq *JobSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jsq.Limit(1).IDs(setContextOp(ctx, jsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jsq *JobSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := jsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JobSchema entity is found.
// Returns a *NotFoundError when no JobSchema entities are found.
func (jsq *JobSchemaQuery) Only(ctx context.Context) (*JobSchema, error) {
	nodes, err := jsq.Limit(2).All(setContextOp(ctx, jsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobschema.Label}
	default:
		return nil, &NotSingularError{jobschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jsq *JobSchemaQuery) OnlyX(ctx context.Context) *JobSchema {
	node, err := jsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobSchema ID in the query.
// Returns a *NotSingularError when more than one JobSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (jsq *JobSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jsq.Limit(2).IDs(setContextOp(ctx, jsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobschema.Label}
	default:
		err = &NotSingularError{jobschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jsq *JobSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := jsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobSchemas.
func (jsq *JobSchemaQuery) All(ctx context.Context) ([]*JobSchema, error) {
	ctx = setContextOp(ctx, jsq.ctx, "All")
	if err := jsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JobSchema, *JobSchemaQuery]()
	return withInterceptors[[]*JobSchema](ctx, jsq, qr, jsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jsq *JobSchemaQuery) AllX(ctx context.Context) []*JobSchema {
	nodes, err := jsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobSchema IDs.
func (jsq *JobSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if jsq.ctx.Unique == nil && jsq.path != nil {
		jsq.Unique(true)
	}
	ctx = setContextOp(ctx, jsq.ctx, "IDs")
	if err = jsq.Select(jobschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jsq *JobSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := jsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jsq *JobSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jsq.ctx, "Count")
	if err := jsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jsq, querierCount[*JobSchemaQuery](), jsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jsq *JobSchemaQuery) CountX(ctx context.Context) int {
	count, err := jsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jsq *JobSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jsq.ctx, "Exist")
	switch _, err := jsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jsq *JobSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := jsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jsq *JobSchemaQuery) Clone() *JobSchemaQuery {
	if jsq == nil {
		return nil
	}
	return &JobSchemaQuery{
		config:     jsq.config,
		ctx:        jsq.ctx.Clone(),
		order:      append([]jobschema.OrderOption{}, jsq.order...),
		inters:     append([]Interceptor{}, jsq.inters...),
		predicates: append([]predicate.JobSchema{}, jsq.predicates...),
		// clone intermediate query.
		sql:  jsq.sql.Clone(),
		path: jsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (jsq *JobSchemaQuery) GroupBy(field string, fields ...string) *JobSchemaGroupBy {
	jsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JobSchemaGroupBy{build: jsq}
	grbuild.flds = &jsq.ctx.Fields
	grbuild.label = jobschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (jsq *JobSchemaQuery) Select(fields ...string) *JobSchemaSelect {
	jsq.ctx.Fields = append(jsq.ctx.Fields, fields...)
	sbuild := &JobSchemaSelect{JobSchemaQuery: jsq}
	sbuild.label = jobschema.Label
	sbuild.flds, sbuild.scan = &jsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JobSchemaSelect configured with the given aggregations.
func (jsq *JobSchemaQuery) Aggregate(fns ...AggregateFunc) *JobSchemaSelect {
	return jsq.Select().Aggregate(fns...)
}

func (jsq *JobSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jsq); err != nil {
				return err
			}
		}
	}
	for _, f := range jsq.ctx.Fields {
		if !jobschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jsq.path != nil {
		prev, err := jsq.path(ctx)
		if err != nil {
			return err
		}
		jsq.sql = prev
	}
	return nil
}

func (jsq *JobSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JobSchema, error) {
	var (
		nodes = []*JobSchema{}
		_spec = jsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JobSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JobSchema{config: jsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (jsq *JobSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jsq.querySpec()
	_spec.Node.Columns = jsq.ctx.Fields
	if len(jsq.ctx.Fields) > 0 {
		_spec.Unique = jsq.ctx.Unique != nil && *jsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jsq.driver, _spec)
}

func (jsq *JobSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jobschema.Table, jobschema.Columns, sqlgraph.NewFieldSpec(jobschema.FieldID, field.TypeInt))
	_spec.From = jsq.sql
	if unique := jsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if jsq.path != nil {
		_spec.Unique = true
	}
	if fields := jsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobschema.FieldID)
		for i := range fields {
			if fields[i] != jobschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jsq *JobSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jsq.driver.Dialect())
	t1 := builder.Table(jobschema.Table)
	columns := jsq.ctx.Fields
	if len(columns) == 0 {
		columns = jobschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jsq.sql != nil {
		selector = jsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jsq.ctx.Unique != nil && *jsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jsq.predicates {
		p(selector)
	}
	for _, p := range jsq.order {
		p(selector)
	}
	if offset := jsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JobSchemaGroupBy is the group-by builder for JobSchema entities.
type JobSchemaGroupBy struct {
	selector
	build *JobSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jsgb *JobSchemaGroupBy) Aggregate(fns ...AggregateFunc) *JobSchemaGroupBy {
	jsgb.fns = append(jsgb.fns, fns...)
	return jsgb
}

// Scan applies the selector query and scans the result into the given value.
func (jsgb *JobSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jsgb.build.ctx, "GroupBy")
	if err := jsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobSchemaQuery, *JobSchemaGroupBy](ctx, jsgb.build, jsgb, jsgb.build.inters, v)
}

func (jsgb *JobSchemaGroupBy) sqlScan(ctx context.Context, root *JobSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jsgb.fns))
	for _, fn := range jsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jsgb.flds)+len(jsgb.fns))
		for _, f := range *jsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JobSchemaSelect is the builder for selecting fields of JobSchema entities.
type JobSchemaSelect struct {
	*JobSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (jss *JobSchemaSelect) Aggregate(fns ...AggregateFunc) *JobSchemaSelect {
	jss.fns = append(jss.fns, fns...)
	return jss
}

// Scan applies the selector query and scans the result into the given value.
func (jss *JobSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jss.ctx, "Select")
	if err := jss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobSchemaQuery, *JobSchemaSelect](ctx, jss.JobSchemaQuery, jss, jss.inters, v)
}

func (jss *JobSchemaSelect) sqlScan(ctx context.Context, root *JobSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(jss.fns))
	for _, fn := range jss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*jss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
