// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/leetcodeschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LeetcodeSchemaDelete is the builder for deleting a LeetcodeSchema entity.
type LeetcodeSchemaDelete struct {
	config
	hooks    []Hook
	mutation *LeetcodeSchemaMutation
}

// Where appends a list predicates to the LeetcodeSchemaDelete builder.
func (lsd *LeetcodeSchemaDelete) Where(ps ...predicate.LeetcodeSchema) *LeetcodeSchemaDelete {
	lsd.mutation.Where(ps...)
	return lsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lsd *LeetcodeSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lsd.sqlExec, lsd.mutation, lsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lsd *LeetcodeSchemaDelete) ExecX(ctx context.Context) int {
	n, err := lsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lsd *LeetcodeSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(leetcodeschema.Table, sqlgraph.NewFieldSpec(leetcodeschema.FieldID, field.TypeInt))
	if ps := lsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lsd.mutation.done = true
	return affected, err
}

// LeetcodeSchemaDeleteOne is the builder for deleting a single LeetcodeSchema entity.
type LeetcodeSchemaDeleteOne struct {
	lsd *LeetcodeSchemaDelete
}

// Where appends a list predicates to the LeetcodeSchemaDelete builder.
func (lsdo *LeetcodeSchemaDeleteOne) Where(ps ...predicate.LeetcodeSchema) *LeetcodeSchemaDeleteOne {
	lsdo.lsd.mutation.Where(ps...)
	return lsdo
}

// Exec executes the deletion query.
func (lsdo *LeetcodeSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := lsdo.lsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{leetcodeschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lsdo *LeetcodeSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := lsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
