// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/logoschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogoSchemaQuery is the builder for querying LogoSchema entities.
type LogoSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []logoschema.OrderOption
	inters     []Interceptor
	predicates []predicate.LogoSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LogoSchemaQuery builder.
func (lsq *LogoSchemaQuery) Where(ps ...predicate.LogoSchema) *LogoSchemaQuery {
	lsq.predicates = append(lsq.predicates, ps...)
	return lsq
}

// Limit the number of records to be returned by this query.
func (lsq *LogoSchemaQuery) Limit(limit int) *LogoSchemaQuery {
	lsq.ctx.Limit = &limit
	return lsq
}

// Offset to start from.
func (lsq *LogoSchemaQuery) Offset(offset int) *LogoSchemaQuery {
	lsq.ctx.Offset = &offset
	return lsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lsq *LogoSchemaQuery) Unique(unique bool) *LogoSchemaQuery {
	lsq.ctx.Unique = &unique
	return lsq
}

// Order specifies how the records should be ordered.
func (lsq *LogoSchemaQuery) Order(o ...logoschema.OrderOption) *LogoSchemaQuery {
	lsq.order = append(lsq.order, o...)
	return lsq
}

// First returns the first LogoSchema entity from the query.
// Returns a *NotFoundError when no LogoSchema was found.
func (lsq *LogoSchemaQuery) First(ctx context.Context) (*LogoSchema, error) {
	nodes, err := lsq.Limit(1).All(setContextOp(ctx, lsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{logoschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lsq *LogoSchemaQuery) FirstX(ctx context.Context) *LogoSchema {
	node, err := lsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LogoSchema ID from the query.
// Returns a *NotFoundError when no LogoSchema ID was found.
func (lsq *LogoSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lsq.Limit(1).IDs(setContextOp(ctx, lsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{logoschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lsq *LogoSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := lsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LogoSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LogoSchema entity is found.
// Returns a *NotFoundError when no LogoSchema entities are found.
func (lsq *LogoSchemaQuery) Only(ctx context.Context) (*LogoSchema, error) {
	nodes, err := lsq.Limit(2).All(setContextOp(ctx, lsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{logoschema.Label}
	default:
		return nil, &NotSingularError{logoschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lsq *LogoSchemaQuery) OnlyX(ctx context.Context) *LogoSchema {
	node, err := lsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LogoSchema ID in the query.
// Returns a *NotSingularError when more than one LogoSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (lsq *LogoSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lsq.Limit(2).IDs(setContextOp(ctx, lsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{logoschema.Label}
	default:
		err = &NotSingularError{logoschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lsq *LogoSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := lsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LogoSchemas.
func (lsq *LogoSchemaQuery) All(ctx context.Context) ([]*LogoSchema, error) {
	ctx = setContextOp(ctx, lsq.ctx, "All")
	if err := lsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LogoSchema, *LogoSchemaQuery]()
	return withInterceptors[[]*LogoSchema](ctx, lsq, qr, lsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lsq *LogoSchemaQuery) AllX(ctx context.Context) []*LogoSchema {
	nodes, err := lsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LogoSchema IDs.
func (lsq *LogoSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lsq.ctx.Unique == nil && lsq.path != nil {
		lsq.Unique(true)
	}
	ctx = setContextOp(ctx, lsq.ctx, "IDs")
	if err = lsq.Select(logoschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lsq *LogoSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := lsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lsq *LogoSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lsq.ctx, "Count")
	if err := lsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lsq, querierCount[*LogoSchemaQuery](), lsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lsq *LogoSchemaQuery) CountX(ctx context.Context) int {
	count, err := lsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lsq *LogoSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lsq.ctx, "Exist")
	switch _, err := lsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lsq *LogoSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := lsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LogoSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lsq *LogoSchemaQuery) Clone() *LogoSchemaQuery {
	if lsq == nil {
		return nil
	}
	return &LogoSchemaQuery{
		config:     lsq.config,
		ctx:        lsq.ctx.Clone(),
		order:      append([]logoschema.OrderOption{}, lsq.order...),
		inters:     append([]Interceptor{}, lsq.inters...),
		predicates: append([]predicate.LogoSchema{}, lsq.predicates...),
		// clone intermediate query.
		sql:  lsq.sql.Clone(),
		path: lsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (lsq *LogoSchemaQuery) GroupBy(field string, fields ...string) *LogoSchemaGroupBy {
	lsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LogoSchemaGroupBy{build: lsq}
	grbuild.flds = &lsq.ctx.Fields
	grbuild.label = logoschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (lsq *LogoSchemaQuery) Select(fields ...string) *LogoSchemaSelect {
	lsq.ctx.Fields = append(lsq.ctx.Fields, fields...)
	sbuild := &LogoSchemaSelect{LogoSchemaQuery: lsq}
	sbuild.label = logoschema.Label
	sbuild.flds, sbuild.scan = &lsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LogoSchemaSelect configured with the given aggregations.
func (lsq *LogoSchemaQuery) Aggregate(fns ...AggregateFunc) *LogoSchemaSelect {
	return lsq.Select().Aggregate(fns...)
}

func (lsq *LogoSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lsq); err != nil {
				return err
			}
		}
	}
	for _, f := range lsq.ctx.Fields {
		if !logoschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lsq.path != nil {
		prev, err := lsq.path(ctx)
		if err != nil {
			return err
		}
		lsq.sql = prev
	}
	return nil
}

func (lsq *LogoSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LogoSchema, error) {
	var (
		nodes = []*LogoSchema{}
		_spec = lsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LogoSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LogoSchema{config: lsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lsq *LogoSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lsq.querySpec()
	_spec.Node.Columns = lsq.ctx.Fields
	if len(lsq.ctx.Fields) > 0 {
		_spec.Unique = lsq.ctx.Unique != nil && *lsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lsq.driver, _spec)
}

func (lsq *LogoSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(logoschema.Table, logoschema.Columns, sqlgraph.NewFieldSpec(logoschema.FieldID, field.TypeInt))
	_spec.From = lsq.sql
	if unique := lsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lsq.path != nil {
		_spec.Unique = true
	}
	if fields := lsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logoschema.FieldID)
		for i := range fields {
			if fields[i] != logoschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lsq *LogoSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lsq.driver.Dialect())
	t1 := builder.Table(logoschema.Table)
	columns := lsq.ctx.Fields
	if len(columns) == 0 {
		columns = logoschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lsq.sql != nil {
		selector = lsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lsq.ctx.Unique != nil && *lsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lsq.predicates {
		p(selector)
	}
	for _, p := range lsq.order {
		p(selector)
	}
	if offset := lsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LogoSchemaGroupBy is the group-by builder for LogoSchema entities.
type LogoSchemaGroupBy struct {
	selector
	build *LogoSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lsgb *LogoSchemaGroupBy) Aggregate(fns ...AggregateFunc) *LogoSchemaGroupBy {
	lsgb.fns = append(lsgb.fns, fns...)
	return lsgb
}

// Scan applies the selector query and scans the result into the given value.
func (lsgb *LogoSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lsgb.build.ctx, "GroupBy")
	if err := lsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LogoSchemaQuery, *LogoSchemaGroupBy](ctx, lsgb.build, lsgb, lsgb.build.inters, v)
}

func (lsgb *LogoSchemaGroupBy) sqlScan(ctx context.Context, root *LogoSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lsgb.fns))
	for _, fn := range lsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lsgb.flds)+len(lsgb.fns))
		for _, f := range *lsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LogoSchemaSelect is the builder for selecting fields of LogoSchema entities.
type LogoSchemaSelect struct {
	*LogoSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lss *LogoSchemaSelect) Aggregate(fns ...AggregateFunc) *LogoSchemaSelect {
	lss.fns = append(lss.fns, fns...)
	return lss
}

// Scan applies the selector query and scans the result into the given value.
func (lss *LogoSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lss.ctx, "Select")
	if err := lss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LogoSchemaQuery, *LogoSchemaSelect](ctx, lss.LogoSchemaQuery, lss, lss.inters, v)
}

func (lss *LogoSchemaSelect) sqlScan(ctx context.Context, root *LogoSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lss.fns))
	for _, fn := range lss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
