// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/namecardschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NamecardSchemaDelete is the builder for deleting a NamecardSchema entity.
type NamecardSchemaDelete struct {
	config
	hooks    []Hook
	mutation *NamecardSchemaMutation
}

// Where appends a list predicates to the NamecardSchemaDelete builder.
func (nsd *NamecardSchemaDelete) Where(ps ...predicate.NamecardSchema) *NamecardSchemaDelete {
	nsd.mutation.Where(ps...)
	return nsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nsd *NamecardSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nsd.sqlExec, nsd.mutation, nsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nsd *NamecardSchemaDelete) ExecX(ctx context.Context) int {
	n, err := nsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nsd *NamecardSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(namecardschema.Table, sqlgraph.NewFieldSpec(namecardschema.FieldID, field.TypeInt))
	if ps := nsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nsd.mutation.done = true
	return affected, err
}

// NamecardSchemaDeleteOne is the builder for deleting a single NamecardSchema entity.
type NamecardSchemaDeleteOne struct {
	nsd *NamecardSchemaDelete
}

// Where appends a list predicates to the NamecardSchemaDelete builder.
func (nsdo *NamecardSchemaDeleteOne) Where(ps ...predicate.NamecardSchema) *NamecardSchemaDeleteOne {
	nsdo.nsd.mutation.Where(ps...)
	return nsdo
}

// Exec executes the deletion query.
func (nsdo *NamecardSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := nsdo.nsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{namecardschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nsdo *NamecardSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := nsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
