// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/notificationschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationSchemaDelete is the builder for deleting a NotificationSchema entity.
type NotificationSchemaDelete struct {
	config
	hooks    []Hook
	mutation *NotificationSchemaMutation
}

// Where appends a list predicates to the NotificationSchemaDelete builder.
func (nsd *NotificationSchemaDelete) Where(ps ...predicate.NotificationSchema) *NotificationSchemaDelete {
	nsd.mutation.Where(ps...)
	return nsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nsd *NotificationSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nsd.sqlExec, nsd.mutation, nsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nsd *NotificationSchemaDelete) ExecX(ctx context.Context) int {
	n, err := nsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nsd *NotificationSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(notificationschema.Table, sqlgraph.NewFieldSpec(notificationschema.FieldID, field.TypeInt))
	if ps := nsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nsd.mutation.done = true
	return affected, err
}

// NotificationSchemaDeleteOne is the builder for deleting a single NotificationSchema entity.
type NotificationSchemaDeleteOne struct {
	nsd *NotificationSchemaDelete
}

// Where appends a list predicates to the NotificationSchemaDelete builder.
func (nsdo *NotificationSchemaDeleteOne) Where(ps ...predicate.NotificationSchema) *NotificationSchemaDeleteOne {
	nsdo.nsd.mutation.Where(ps...)
	return nsdo
}

// Exec executes the deletion query.
func (nsdo *NotificationSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := nsdo.nsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{notificationschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nsdo *NotificationSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := nsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
