// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/personalizationschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PersonalizationSchemaDelete is the builder for deleting a PersonalizationSchema entity.
type PersonalizationSchemaDelete struct {
	config
	hooks    []Hook
	mutation *PersonalizationSchemaMutation
}

// Where appends a list predicates to the PersonalizationSchemaDelete builder.
func (psd *PersonalizationSchemaDelete) Where(ps ...predicate.PersonalizationSchema) *PersonalizationSchemaDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *PersonalizationSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *PersonalizationSchemaDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *PersonalizationSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(personalizationschema.Table, sqlgraph.NewFieldSpec(personalizationschema.FieldID, field.TypeInt))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// PersonalizationSchemaDeleteOne is the builder for deleting a single PersonalizationSchema entity.
type PersonalizationSchemaDeleteOne struct {
	psd *PersonalizationSchemaDelete
}

// Where appends a list predicates to the PersonalizationSchemaDelete builder.
func (psdo *PersonalizationSchemaDeleteOne) Where(ps ...predicate.PersonalizationSchema) *PersonalizationSchemaDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *PersonalizationSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{personalizationschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *PersonalizationSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
