// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"persona/libs/database/ent/portfolioschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PortfolioSchemaUpdate is the builder for updating PortfolioSchema entities.
type PortfolioSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *PortfolioSchemaMutation
}

// Where appends a list predicates to the PortfolioSchemaUpdate builder.
func (psu *PortfolioSchemaUpdate) Where(ps ...predicate.PortfolioSchema) *PortfolioSchemaUpdate {
	psu.mutation.Where(ps...)
	return psu
}

// Mutation returns the PortfolioSchemaMutation object of the builder.
func (psu *PortfolioSchemaUpdate) Mutation() *PortfolioSchemaMutation {
	return psu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (psu *PortfolioSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, psu.sqlSave, psu.mutation, psu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psu *PortfolioSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := psu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (psu *PortfolioSchemaUpdate) Exec(ctx context.Context) error {
	_, err := psu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psu *PortfolioSchemaUpdate) ExecX(ctx context.Context) {
	if err := psu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psu *PortfolioSchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(portfolioschema.Table, portfolioschema.Columns, sqlgraph.NewFieldSpec(portfolioschema.FieldID, field.TypeInt))
	if ps := psu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, psu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfolioschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	psu.mutation.done = true
	return n, nil
}

// PortfolioSchemaUpdateOne is the builder for updating a single PortfolioSchema entity.
type PortfolioSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PortfolioSchemaMutation
}

// Mutation returns the PortfolioSchemaMutation object of the builder.
func (psuo *PortfolioSchemaUpdateOne) Mutation() *PortfolioSchemaMutation {
	return psuo.mutation
}

// Where appends a list predicates to the PortfolioSchemaUpdate builder.
func (psuo *PortfolioSchemaUpdateOne) Where(ps ...predicate.PortfolioSchema) *PortfolioSchemaUpdateOne {
	psuo.mutation.Where(ps...)
	return psuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (psuo *PortfolioSchemaUpdateOne) Select(field string, fields ...string) *PortfolioSchemaUpdateOne {
	psuo.fields = append([]string{field}, fields...)
	return psuo
}

// Save executes the query and returns the updated PortfolioSchema entity.
func (psuo *PortfolioSchemaUpdateOne) Save(ctx context.Context) (*PortfolioSchema, error) {
	return withHooks(ctx, psuo.sqlSave, psuo.mutation, psuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (psuo *PortfolioSchemaUpdateOne) SaveX(ctx context.Context) *PortfolioSchema {
	node, err := psuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (psuo *PortfolioSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := psuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psuo *PortfolioSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := psuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (psuo *PortfolioSchemaUpdateOne) sqlSave(ctx context.Context) (_node *PortfolioSchema, err error) {
	_spec := sqlgraph.NewUpdateSpec(portfolioschema.Table, portfolioschema.Columns, sqlgraph.NewFieldSpec(portfolioschema.FieldID, field.TypeInt))
	id, ok := psuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PortfolioSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := psuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portfolioschema.FieldID)
		for _, f := range fields {
			if !portfolioschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != portfolioschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := psuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &PortfolioSchema{config: psuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, psuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfolioschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	psuo.mutation.done = true
	return _node, nil
}
