// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/portfolioschema"
	"persona/libs/database/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PortfolioSchemaDelete is the builder for deleting a PortfolioSchema entity.
type PortfolioSchemaDelete struct {
	config
	hooks    []Hook
	mutation *PortfolioSchemaMutation
}

// Where appends a list predicates to the PortfolioSchemaDelete builder.
func (psd *PortfolioSchemaDelete) Where(ps ...predicate.PortfolioSchema) *PortfolioSchemaDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *PortfolioSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *PortfolioSchemaDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *PortfolioSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(portfolioschema.Table, sqlgraph.NewFieldSpec(portfolioschema.FieldID, field.TypeInt))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// PortfolioSchemaDeleteOne is the builder for deleting a single PortfolioSchema entity.
type PortfolioSchemaDeleteOne struct {
	psd *PortfolioSchemaDelete
}

// Where appends a list predicates to the PortfolioSchemaDelete builder.
func (psdo *PortfolioSchemaDeleteOne) Where(ps ...predicate.PortfolioSchema) *PortfolioSchemaDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *PortfolioSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{portfolioschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *PortfolioSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
