// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"persona/libs/database/ent/phoneschema"
	"persona/libs/database/ent/photoschema"
	"persona/libs/database/ent/profileschema"
	"persona/libs/database/ent/userschema"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileSchemaCreate is the builder for creating a ProfileSchema entity.
type ProfileSchemaCreate struct {
	config
	mutation *ProfileSchemaMutation
	hooks    []Hook
}

// SetOwnerID sets the "owner" edge to the UserSchema entity by ID.
func (psc *ProfileSchemaCreate) SetOwnerID(id int) *ProfileSchemaCreate {
	psc.mutation.SetOwnerID(id)
	return psc
}

// SetOwner sets the "owner" edge to the UserSchema entity.
func (psc *ProfileSchemaCreate) SetOwner(u *UserSchema) *ProfileSchemaCreate {
	return psc.SetOwnerID(u.ID)
}

// SetPhotoID sets the "photo" edge to the PhotoSchema entity by ID.
func (psc *ProfileSchemaCreate) SetPhotoID(id int) *ProfileSchemaCreate {
	psc.mutation.SetPhotoID(id)
	return psc
}

// SetNillablePhotoID sets the "photo" edge to the PhotoSchema entity by ID if the given value is not nil.
func (psc *ProfileSchemaCreate) SetNillablePhotoID(id *int) *ProfileSchemaCreate {
	if id != nil {
		psc = psc.SetPhotoID(*id)
	}
	return psc
}

// SetPhoto sets the "photo" edge to the PhotoSchema entity.
func (psc *ProfileSchemaCreate) SetPhoto(p *PhotoSchema) *ProfileSchemaCreate {
	return psc.SetPhotoID(p.ID)
}

// SetPhoneID sets the "phone" edge to the PhoneSchema entity by ID.
func (psc *ProfileSchemaCreate) SetPhoneID(id int) *ProfileSchemaCreate {
	psc.mutation.SetPhoneID(id)
	return psc
}

// SetNillablePhoneID sets the "phone" edge to the PhoneSchema entity by ID if the given value is not nil.
func (psc *ProfileSchemaCreate) SetNillablePhoneID(id *int) *ProfileSchemaCreate {
	if id != nil {
		psc = psc.SetPhoneID(*id)
	}
	return psc
}

// SetPhone sets the "phone" edge to the PhoneSchema entity.
func (psc *ProfileSchemaCreate) SetPhone(p *PhoneSchema) *ProfileSchemaCreate {
	return psc.SetPhoneID(p.ID)
}

// Mutation returns the ProfileSchemaMutation object of the builder.
func (psc *ProfileSchemaCreate) Mutation() *ProfileSchemaMutation {
	return psc.mutation
}

// Save creates the ProfileSchema in the database.
func (psc *ProfileSchemaCreate) Save(ctx context.Context) (*ProfileSchema, error) {
	return withHooks(ctx, psc.sqlSave, psc.mutation, psc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (psc *ProfileSchemaCreate) SaveX(ctx context.Context) *ProfileSchema {
	v, err := psc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psc *ProfileSchemaCreate) Exec(ctx context.Context) error {
	_, err := psc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psc *ProfileSchemaCreate) ExecX(ctx context.Context) {
	if err := psc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psc *ProfileSchemaCreate) check() error {
	if _, ok := psc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "ProfileSchema.owner"`)}
	}
	return nil
}

func (psc *ProfileSchemaCreate) sqlSave(ctx context.Context) (*ProfileSchema, error) {
	if err := psc.check(); err != nil {
		return nil, err
	}
	_node, _spec := psc.createSpec()
	if err := sqlgraph.CreateNode(ctx, psc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	psc.mutation.id = &_node.ID
	psc.mutation.done = true
	return _node, nil
}

func (psc *ProfileSchemaCreate) createSpec() (*ProfileSchema, *sqlgraph.CreateSpec) {
	var (
		_node = &ProfileSchema{config: psc.config}
		_spec = sqlgraph.NewCreateSpec(profileschema.Table, sqlgraph.NewFieldSpec(profileschema.FieldID, field.TypeInt))
	)
	if nodes := psc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   profileschema.OwnerTable,
			Columns: []string{profileschema.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_schema_profile = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := psc.mutation.PhotoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   profileschema.PhotoTable,
			Columns: []string{profileschema.PhotoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(photoschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := psc.mutation.PhoneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   profileschema.PhoneTable,
			Columns: []string{profileschema.PhoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(phoneschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProfileSchemaCreateBulk is the builder for creating many ProfileSchema entities in bulk.
type ProfileSchemaCreateBulk struct {
	config
	builders []*ProfileSchemaCreate
}

// Save creates the ProfileSchema entities in the database.
func (pscb *ProfileSchemaCreateBulk) Save(ctx context.Context) ([]*ProfileSchema, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pscb.builders))
	nodes := make([]*ProfileSchema, len(pscb.builders))
	mutators := make([]Mutator, len(pscb.builders))
	for i := range pscb.builders {
		func(i int, root context.Context) {
			builder := pscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProfileSchemaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pscb *ProfileSchemaCreateBulk) SaveX(ctx context.Context) []*ProfileSchema {
	v, err := pscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pscb *ProfileSchemaCreateBulk) Exec(ctx context.Context) error {
	_, err := pscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pscb *ProfileSchemaCreateBulk) ExecX(ctx context.Context) {
	if err := pscb.Exec(ctx); err != nil {
		panic(err)
	}
}
