// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"persona/libs/database/ent/predicate"
	"persona/libs/database/ent/profileschema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileSchemaDelete is the builder for deleting a ProfileSchema entity.
type ProfileSchemaDelete struct {
	config
	hooks    []Hook
	mutation *ProfileSchemaMutation
}

// Where appends a list predicates to the ProfileSchemaDelete builder.
func (psd *ProfileSchemaDelete) Where(ps ...predicate.ProfileSchema) *ProfileSchemaDelete {
	psd.mutation.Where(ps...)
	return psd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psd *ProfileSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, psd.sqlExec, psd.mutation, psd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (psd *ProfileSchemaDelete) ExecX(ctx context.Context) int {
	n, err := psd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psd *ProfileSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(profileschema.Table, sqlgraph.NewFieldSpec(profileschema.FieldID, field.TypeInt))
	if ps := psd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	psd.mutation.done = true
	return affected, err
}

// ProfileSchemaDeleteOne is the builder for deleting a single ProfileSchema entity.
type ProfileSchemaDeleteOne struct {
	psd *ProfileSchemaDelete
}

// Where appends a list predicates to the ProfileSchemaDelete builder.
func (psdo *ProfileSchemaDeleteOne) Where(ps ...predicate.ProfileSchema) *ProfileSchemaDeleteOne {
	psdo.psd.mutation.Where(ps...)
	return psdo
}

// Exec executes the deletion query.
func (psdo *ProfileSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := psdo.psd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{profileschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psdo *ProfileSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := psdo.Exec(ctx); err != nil {
		panic(err)
	}
}
