// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/predicate"
	"persona/libs/database/ent/resumeschema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeSchemaQuery is the builder for querying ResumeSchema entities.
type ResumeSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []resumeschema.OrderOption
	inters     []Interceptor
	predicates []predicate.ResumeSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResumeSchemaQuery builder.
func (rsq *ResumeSchemaQuery) Where(ps ...predicate.ResumeSchema) *ResumeSchemaQuery {
	rsq.predicates = append(rsq.predicates, ps...)
	return rsq
}

// Limit the number of records to be returned by this query.
func (rsq *ResumeSchemaQuery) Limit(limit int) *ResumeSchemaQuery {
	rsq.ctx.Limit = &limit
	return rsq
}

// Offset to start from.
func (rsq *ResumeSchemaQuery) Offset(offset int) *ResumeSchemaQuery {
	rsq.ctx.Offset = &offset
	return rsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rsq *ResumeSchemaQuery) Unique(unique bool) *ResumeSchemaQuery {
	rsq.ctx.Unique = &unique
	return rsq
}

// Order specifies how the records should be ordered.
func (rsq *ResumeSchemaQuery) Order(o ...resumeschema.OrderOption) *ResumeSchemaQuery {
	rsq.order = append(rsq.order, o...)
	return rsq
}

// First returns the first ResumeSchema entity from the query.
// Returns a *NotFoundError when no ResumeSchema was found.
func (rsq *ResumeSchemaQuery) First(ctx context.Context) (*ResumeSchema, error) {
	nodes, err := rsq.Limit(1).All(setContextOp(ctx, rsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resumeschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) FirstX(ctx context.Context) *ResumeSchema {
	node, err := rsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ResumeSchema ID from the query.
// Returns a *NotFoundError when no ResumeSchema ID was found.
func (rsq *ResumeSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(1).IDs(setContextOp(ctx, rsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resumeschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := rsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ResumeSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ResumeSchema entity is found.
// Returns a *NotFoundError when no ResumeSchema entities are found.
func (rsq *ResumeSchemaQuery) Only(ctx context.Context) (*ResumeSchema, error) {
	nodes, err := rsq.Limit(2).All(setContextOp(ctx, rsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resumeschema.Label}
	default:
		return nil, &NotSingularError{resumeschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) OnlyX(ctx context.Context) *ResumeSchema {
	node, err := rsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ResumeSchema ID in the query.
// Returns a *NotSingularError when more than one ResumeSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (rsq *ResumeSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(2).IDs(setContextOp(ctx, rsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resumeschema.Label}
	default:
		err = &NotSingularError{resumeschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := rsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ResumeSchemas.
func (rsq *ResumeSchemaQuery) All(ctx context.Context) ([]*ResumeSchema, error) {
	ctx = setContextOp(ctx, rsq.ctx, "All")
	if err := rsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ResumeSchema, *ResumeSchemaQuery]()
	return withInterceptors[[]*ResumeSchema](ctx, rsq, qr, rsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) AllX(ctx context.Context) []*ResumeSchema {
	nodes, err := rsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ResumeSchema IDs.
func (rsq *ResumeSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rsq.ctx.Unique == nil && rsq.path != nil {
		rsq.Unique(true)
	}
	ctx = setContextOp(ctx, rsq.ctx, "IDs")
	if err = rsq.Select(resumeschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := rsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rsq *ResumeSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rsq.ctx, "Count")
	if err := rsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rsq, querierCount[*ResumeSchemaQuery](), rsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) CountX(ctx context.Context) int {
	count, err := rsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rsq *ResumeSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rsq.ctx, "Exist")
	switch _, err := rsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rsq *ResumeSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := rsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResumeSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rsq *ResumeSchemaQuery) Clone() *ResumeSchemaQuery {
	if rsq == nil {
		return nil
	}
	return &ResumeSchemaQuery{
		config:     rsq.config,
		ctx:        rsq.ctx.Clone(),
		order:      append([]resumeschema.OrderOption{}, rsq.order...),
		inters:     append([]Interceptor{}, rsq.inters...),
		predicates: append([]predicate.ResumeSchema{}, rsq.predicates...),
		// clone intermediate query.
		sql:  rsq.sql.Clone(),
		path: rsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (rsq *ResumeSchemaQuery) GroupBy(field string, fields ...string) *ResumeSchemaGroupBy {
	rsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResumeSchemaGroupBy{build: rsq}
	grbuild.flds = &rsq.ctx.Fields
	grbuild.label = resumeschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (rsq *ResumeSchemaQuery) Select(fields ...string) *ResumeSchemaSelect {
	rsq.ctx.Fields = append(rsq.ctx.Fields, fields...)
	sbuild := &ResumeSchemaSelect{ResumeSchemaQuery: rsq}
	sbuild.label = resumeschema.Label
	sbuild.flds, sbuild.scan = &rsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResumeSchemaSelect configured with the given aggregations.
func (rsq *ResumeSchemaQuery) Aggregate(fns ...AggregateFunc) *ResumeSchemaSelect {
	return rsq.Select().Aggregate(fns...)
}

func (rsq *ResumeSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rsq); err != nil {
				return err
			}
		}
	}
	for _, f := range rsq.ctx.Fields {
		if !resumeschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rsq.path != nil {
		prev, err := rsq.path(ctx)
		if err != nil {
			return err
		}
		rsq.sql = prev
	}
	return nil
}

func (rsq *ResumeSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ResumeSchema, error) {
	var (
		nodes = []*ResumeSchema{}
		_spec = rsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ResumeSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ResumeSchema{config: rsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rsq *ResumeSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rsq.querySpec()
	_spec.Node.Columns = rsq.ctx.Fields
	if len(rsq.ctx.Fields) > 0 {
		_spec.Unique = rsq.ctx.Unique != nil && *rsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rsq.driver, _spec)
}

func (rsq *ResumeSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(resumeschema.Table, resumeschema.Columns, sqlgraph.NewFieldSpec(resumeschema.FieldID, field.TypeInt))
	_spec.From = rsq.sql
	if unique := rsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rsq.path != nil {
		_spec.Unique = true
	}
	if fields := rsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resumeschema.FieldID)
		for i := range fields {
			if fields[i] != resumeschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rsq *ResumeSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rsq.driver.Dialect())
	t1 := builder.Table(resumeschema.Table)
	columns := rsq.ctx.Fields
	if len(columns) == 0 {
		columns = resumeschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rsq.sql != nil {
		selector = rsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rsq.ctx.Unique != nil && *rsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rsq.predicates {
		p(selector)
	}
	for _, p := range rsq.order {
		p(selector)
	}
	if offset := rsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResumeSchemaGroupBy is the group-by builder for ResumeSchema entities.
type ResumeSchemaGroupBy struct {
	selector
	build *ResumeSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rsgb *ResumeSchemaGroupBy) Aggregate(fns ...AggregateFunc) *ResumeSchemaGroupBy {
	rsgb.fns = append(rsgb.fns, fns...)
	return rsgb
}

// Scan applies the selector query and scans the result into the given value.
func (rsgb *ResumeSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rsgb.build.ctx, "GroupBy")
	if err := rsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResumeSchemaQuery, *ResumeSchemaGroupBy](ctx, rsgb.build, rsgb, rsgb.build.inters, v)
}

func (rsgb *ResumeSchemaGroupBy) sqlScan(ctx context.Context, root *ResumeSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rsgb.fns))
	for _, fn := range rsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rsgb.flds)+len(rsgb.fns))
		for _, f := range *rsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResumeSchemaSelect is the builder for selecting fields of ResumeSchema entities.
type ResumeSchemaSelect struct {
	*ResumeSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rss *ResumeSchemaSelect) Aggregate(fns ...AggregateFunc) *ResumeSchemaSelect {
	rss.fns = append(rss.fns, fns...)
	return rss
}

// Scan applies the selector query and scans the result into the given value.
func (rss *ResumeSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rss.ctx, "Select")
	if err := rss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResumeSchemaQuery, *ResumeSchemaSelect](ctx, rss.ResumeSchemaQuery, rss, rss.inters, v)
}

func (rss *ResumeSchemaSelect) sqlScan(ctx context.Context, root *ResumeSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rss.fns))
	for _, fn := range rss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
