// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/predicate"
	"persona/libs/database/ent/roleschema"
	"persona/libs/database/ent/userschema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoleSchemaQuery is the builder for querying RoleSchema entities.
type RoleSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []roleschema.OrderOption
	inters     []Interceptor
	predicates []predicate.RoleSchema
	withUser   *UserSchemaQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoleSchemaQuery builder.
func (rsq *RoleSchemaQuery) Where(ps ...predicate.RoleSchema) *RoleSchemaQuery {
	rsq.predicates = append(rsq.predicates, ps...)
	return rsq
}

// Limit the number of records to be returned by this query.
func (rsq *RoleSchemaQuery) Limit(limit int) *RoleSchemaQuery {
	rsq.ctx.Limit = &limit
	return rsq
}

// Offset to start from.
func (rsq *RoleSchemaQuery) Offset(offset int) *RoleSchemaQuery {
	rsq.ctx.Offset = &offset
	return rsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rsq *RoleSchemaQuery) Unique(unique bool) *RoleSchemaQuery {
	rsq.ctx.Unique = &unique
	return rsq
}

// Order specifies how the records should be ordered.
func (rsq *RoleSchemaQuery) Order(o ...roleschema.OrderOption) *RoleSchemaQuery {
	rsq.order = append(rsq.order, o...)
	return rsq
}

// QueryUser chains the current query on the "user" edge.
func (rsq *RoleSchemaQuery) QueryUser() *UserSchemaQuery {
	query := (&UserSchemaClient{config: rsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roleschema.Table, roleschema.FieldID, selector),
			sqlgraph.To(userschema.Table, userschema.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, roleschema.UserTable, roleschema.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(rsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoleSchema entity from the query.
// Returns a *NotFoundError when no RoleSchema was found.
func (rsq *RoleSchemaQuery) First(ctx context.Context) (*RoleSchema, error) {
	nodes, err := rsq.Limit(1).All(setContextOp(ctx, rsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roleschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rsq *RoleSchemaQuery) FirstX(ctx context.Context) *RoleSchema {
	node, err := rsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoleSchema ID from the query.
// Returns a *NotFoundError when no RoleSchema ID was found.
func (rsq *RoleSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(1).IDs(setContextOp(ctx, rsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roleschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rsq *RoleSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := rsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoleSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoleSchema entity is found.
// Returns a *NotFoundError when no RoleSchema entities are found.
func (rsq *RoleSchemaQuery) Only(ctx context.Context) (*RoleSchema, error) {
	nodes, err := rsq.Limit(2).All(setContextOp(ctx, rsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roleschema.Label}
	default:
		return nil, &NotSingularError{roleschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rsq *RoleSchemaQuery) OnlyX(ctx context.Context) *RoleSchema {
	node, err := rsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoleSchema ID in the query.
// Returns a *NotSingularError when more than one RoleSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (rsq *RoleSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(2).IDs(setContextOp(ctx, rsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roleschema.Label}
	default:
		err = &NotSingularError{roleschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rsq *RoleSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := rsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoleSchemas.
func (rsq *RoleSchemaQuery) All(ctx context.Context) ([]*RoleSchema, error) {
	ctx = setContextOp(ctx, rsq.ctx, "All")
	if err := rsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoleSchema, *RoleSchemaQuery]()
	return withInterceptors[[]*RoleSchema](ctx, rsq, qr, rsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rsq *RoleSchemaQuery) AllX(ctx context.Context) []*RoleSchema {
	nodes, err := rsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoleSchema IDs.
func (rsq *RoleSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rsq.ctx.Unique == nil && rsq.path != nil {
		rsq.Unique(true)
	}
	ctx = setContextOp(ctx, rsq.ctx, "IDs")
	if err = rsq.Select(roleschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rsq *RoleSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := rsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rsq *RoleSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rsq.ctx, "Count")
	if err := rsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rsq, querierCount[*RoleSchemaQuery](), rsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rsq *RoleSchemaQuery) CountX(ctx context.Context) int {
	count, err := rsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rsq *RoleSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rsq.ctx, "Exist")
	switch _, err := rsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rsq *RoleSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := rsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoleSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rsq *RoleSchemaQuery) Clone() *RoleSchemaQuery {
	if rsq == nil {
		return nil
	}
	return &RoleSchemaQuery{
		config:     rsq.config,
		ctx:        rsq.ctx.Clone(),
		order:      append([]roleschema.OrderOption{}, rsq.order...),
		inters:     append([]Interceptor{}, rsq.inters...),
		predicates: append([]predicate.RoleSchema{}, rsq.predicates...),
		withUser:   rsq.withUser.Clone(),
		// clone intermediate query.
		sql:  rsq.sql.Clone(),
		path: rsq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (rsq *RoleSchemaQuery) WithUser(opts ...func(*UserSchemaQuery)) *RoleSchemaQuery {
	query := (&UserSchemaClient{config: rsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rsq.withUser = query
	return rsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (rsq *RoleSchemaQuery) GroupBy(field string, fields ...string) *RoleSchemaGroupBy {
	rsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoleSchemaGroupBy{build: rsq}
	grbuild.flds = &rsq.ctx.Fields
	grbuild.label = roleschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (rsq *RoleSchemaQuery) Select(fields ...string) *RoleSchemaSelect {
	rsq.ctx.Fields = append(rsq.ctx.Fields, fields...)
	sbuild := &RoleSchemaSelect{RoleSchemaQuery: rsq}
	sbuild.label = roleschema.Label
	sbuild.flds, sbuild.scan = &rsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoleSchemaSelect configured with the given aggregations.
func (rsq *RoleSchemaQuery) Aggregate(fns ...AggregateFunc) *RoleSchemaSelect {
	return rsq.Select().Aggregate(fns...)
}

func (rsq *RoleSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rsq); err != nil {
				return err
			}
		}
	}
	for _, f := range rsq.ctx.Fields {
		if !roleschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rsq.path != nil {
		prev, err := rsq.path(ctx)
		if err != nil {
			return err
		}
		rsq.sql = prev
	}
	return nil
}

func (rsq *RoleSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoleSchema, error) {
	var (
		nodes       = []*RoleSchema{}
		withFKs     = rsq.withFKs
		_spec       = rsq.querySpec()
		loadedTypes = [1]bool{
			rsq.withUser != nil,
		}
	)
	if rsq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, roleschema.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoleSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoleSchema{config: rsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rsq.withUser; query != nil {
		if err := rsq.loadUser(ctx, query, nodes, nil,
			func(n *RoleSchema, e *UserSchema) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rsq *RoleSchemaQuery) loadUser(ctx context.Context, query *UserSchemaQuery, nodes []*RoleSchema, init func(*RoleSchema), assign func(*RoleSchema, *UserSchema)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RoleSchema)
	for i := range nodes {
		if nodes[i].user_schema_roles == nil {
			continue
		}
		fk := *nodes[i].user_schema_roles
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(userschema.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_schema_roles" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rsq *RoleSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rsq.querySpec()
	_spec.Node.Columns = rsq.ctx.Fields
	if len(rsq.ctx.Fields) > 0 {
		_spec.Unique = rsq.ctx.Unique != nil && *rsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rsq.driver, _spec)
}

func (rsq *RoleSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roleschema.Table, roleschema.Columns, sqlgraph.NewFieldSpec(roleschema.FieldID, field.TypeInt))
	_spec.From = rsq.sql
	if unique := rsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rsq.path != nil {
		_spec.Unique = true
	}
	if fields := rsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roleschema.FieldID)
		for i := range fields {
			if fields[i] != roleschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rsq *RoleSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rsq.driver.Dialect())
	t1 := builder.Table(roleschema.Table)
	columns := rsq.ctx.Fields
	if len(columns) == 0 {
		columns = roleschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rsq.sql != nil {
		selector = rsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rsq.ctx.Unique != nil && *rsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rsq.predicates {
		p(selector)
	}
	for _, p := range rsq.order {
		p(selector)
	}
	if offset := rsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoleSchemaGroupBy is the group-by builder for RoleSchema entities.
type RoleSchemaGroupBy struct {
	selector
	build *RoleSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rsgb *RoleSchemaGroupBy) Aggregate(fns ...AggregateFunc) *RoleSchemaGroupBy {
	rsgb.fns = append(rsgb.fns, fns...)
	return rsgb
}

// Scan applies the selector query and scans the result into the given value.
func (rsgb *RoleSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rsgb.build.ctx, "GroupBy")
	if err := rsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoleSchemaQuery, *RoleSchemaGroupBy](ctx, rsgb.build, rsgb, rsgb.build.inters, v)
}

func (rsgb *RoleSchemaGroupBy) sqlScan(ctx context.Context, root *RoleSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rsgb.fns))
	for _, fn := range rsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rsgb.flds)+len(rsgb.fns))
		for _, f := range *rsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoleSchemaSelect is the builder for selecting fields of RoleSchema entities.
type RoleSchemaSelect struct {
	*RoleSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rss *RoleSchemaSelect) Aggregate(fns ...AggregateFunc) *RoleSchemaSelect {
	rss.fns = append(rss.fns, fns...)
	return rss
}

// Scan applies the selector query and scans the result into the given value.
func (rss *RoleSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rss.ctx, "Select")
	if err := rss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoleSchemaQuery, *RoleSchemaSelect](ctx, rss.RoleSchemaQuery, rss, rss.inters, v)
}

func (rss *RoleSchemaSelect) sqlScan(ctx context.Context, root *RoleSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rss.fns))
	for _, fn := range rss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
