// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"persona/libs/database/ent/predicate"
	"persona/libs/database/ent/roleschema"
	"persona/libs/database/ent/userschema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoleSchemaUpdate is the builder for updating RoleSchema entities.
type RoleSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *RoleSchemaMutation
}

// Where appends a list predicates to the RoleSchemaUpdate builder.
func (rsu *RoleSchemaUpdate) Where(ps ...predicate.RoleSchema) *RoleSchemaUpdate {
	rsu.mutation.Where(ps...)
	return rsu
}

// SetUserID sets the "user" edge to the UserSchema entity by ID.
func (rsu *RoleSchemaUpdate) SetUserID(id int) *RoleSchemaUpdate {
	rsu.mutation.SetUserID(id)
	return rsu
}

// SetNillableUserID sets the "user" edge to the UserSchema entity by ID if the given value is not nil.
func (rsu *RoleSchemaUpdate) SetNillableUserID(id *int) *RoleSchemaUpdate {
	if id != nil {
		rsu = rsu.SetUserID(*id)
	}
	return rsu
}

// SetUser sets the "user" edge to the UserSchema entity.
func (rsu *RoleSchemaUpdate) SetUser(u *UserSchema) *RoleSchemaUpdate {
	return rsu.SetUserID(u.ID)
}

// Mutation returns the RoleSchemaMutation object of the builder.
func (rsu *RoleSchemaUpdate) Mutation() *RoleSchemaMutation {
	return rsu.mutation
}

// ClearUser clears the "user" edge to the UserSchema entity.
func (rsu *RoleSchemaUpdate) ClearUser() *RoleSchemaUpdate {
	rsu.mutation.ClearUser()
	return rsu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rsu *RoleSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rsu.sqlSave, rsu.mutation, rsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rsu *RoleSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := rsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rsu *RoleSchemaUpdate) Exec(ctx context.Context) error {
	_, err := rsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsu *RoleSchemaUpdate) ExecX(ctx context.Context) {
	if err := rsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rsu *RoleSchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(roleschema.Table, roleschema.Columns, sqlgraph.NewFieldSpec(roleschema.FieldID, field.TypeInt))
	if ps := rsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if rsu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roleschema.UserTable,
			Columns: []string{roleschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userschema.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rsu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roleschema.UserTable,
			Columns: []string{roleschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roleschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rsu.mutation.done = true
	return n, nil
}

// RoleSchemaUpdateOne is the builder for updating a single RoleSchema entity.
type RoleSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleSchemaMutation
}

// SetUserID sets the "user" edge to the UserSchema entity by ID.
func (rsuo *RoleSchemaUpdateOne) SetUserID(id int) *RoleSchemaUpdateOne {
	rsuo.mutation.SetUserID(id)
	return rsuo
}

// SetNillableUserID sets the "user" edge to the UserSchema entity by ID if the given value is not nil.
func (rsuo *RoleSchemaUpdateOne) SetNillableUserID(id *int) *RoleSchemaUpdateOne {
	if id != nil {
		rsuo = rsuo.SetUserID(*id)
	}
	return rsuo
}

// SetUser sets the "user" edge to the UserSchema entity.
func (rsuo *RoleSchemaUpdateOne) SetUser(u *UserSchema) *RoleSchemaUpdateOne {
	return rsuo.SetUserID(u.ID)
}

// Mutation returns the RoleSchemaMutation object of the builder.
func (rsuo *RoleSchemaUpdateOne) Mutation() *RoleSchemaMutation {
	return rsuo.mutation
}

// ClearUser clears the "user" edge to the UserSchema entity.
func (rsuo *RoleSchemaUpdateOne) ClearUser() *RoleSchemaUpdateOne {
	rsuo.mutation.ClearUser()
	return rsuo
}

// Where appends a list predicates to the RoleSchemaUpdate builder.
func (rsuo *RoleSchemaUpdateOne) Where(ps ...predicate.RoleSchema) *RoleSchemaUpdateOne {
	rsuo.mutation.Where(ps...)
	return rsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rsuo *RoleSchemaUpdateOne) Select(field string, fields ...string) *RoleSchemaUpdateOne {
	rsuo.fields = append([]string{field}, fields...)
	return rsuo
}

// Save executes the query and returns the updated RoleSchema entity.
func (rsuo *RoleSchemaUpdateOne) Save(ctx context.Context) (*RoleSchema, error) {
	return withHooks(ctx, rsuo.sqlSave, rsuo.mutation, rsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rsuo *RoleSchemaUpdateOne) SaveX(ctx context.Context) *RoleSchema {
	node, err := rsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rsuo *RoleSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := rsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsuo *RoleSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := rsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rsuo *RoleSchemaUpdateOne) sqlSave(ctx context.Context) (_node *RoleSchema, err error) {
	_spec := sqlgraph.NewUpdateSpec(roleschema.Table, roleschema.Columns, sqlgraph.NewFieldSpec(roleschema.FieldID, field.TypeInt))
	id, ok := rsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoleSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roleschema.FieldID)
		for _, f := range fields {
			if !roleschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != roleschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if rsuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roleschema.UserTable,
			Columns: []string{roleschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userschema.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rsuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roleschema.UserTable,
			Columns: []string{roleschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userschema.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RoleSchema{config: rsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roleschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rsuo.mutation.done = true
	return _node, nil
}
