// Code generated by ent, DO NOT EDIT.

package ent

import (
	"persona/libs/database/ent/schema"
	"persona/libs/database/ent/userschema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userschemaFields := schema.UserSchema{}.Fields()
	_ = userschemaFields
	// userschemaDescUUID is the schema descriptor for uuid field.
	userschemaDescUUID := userschemaFields[0].Descriptor()
	// userschema.DefaultUUID holds the default value on creation for the uuid field.
	userschema.DefaultUUID = userschemaDescUUID.Default.(func() uuid.UUID)
	// userschemaDescCreatedAt is the schema descriptor for createdAt field.
	userschemaDescCreatedAt := userschemaFields[4].Descriptor()
	// userschema.DefaultCreatedAt holds the default value on creation for the createdAt field.
	userschema.DefaultCreatedAt = userschemaDescCreatedAt.Default.(func() time.Time)
	// userschemaDescUpdatedAt is the schema descriptor for updatedAt field.
	userschemaDescUpdatedAt := userschemaFields[5].Descriptor()
	// userschema.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	userschema.DefaultUpdatedAt = userschemaDescUpdatedAt.Default.(func() time.Time)
}
