// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"persona/libs/database/ent/predicate"
	"persona/libs/database/ent/subscribeschema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscribeSchemaQuery is the builder for querying SubscribeSchema entities.
type SubscribeSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []subscribeschema.OrderOption
	inters     []Interceptor
	predicates []predicate.SubscribeSchema
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscribeSchemaQuery builder.
func (ssq *SubscribeSchemaQuery) Where(ps ...predicate.SubscribeSchema) *SubscribeSchemaQuery {
	ssq.predicates = append(ssq.predicates, ps...)
	return ssq
}

// Limit the number of records to be returned by this query.
func (ssq *SubscribeSchemaQuery) Limit(limit int) *SubscribeSchemaQuery {
	ssq.ctx.Limit = &limit
	return ssq
}

// Offset to start from.
func (ssq *SubscribeSchemaQuery) Offset(offset int) *SubscribeSchemaQuery {
	ssq.ctx.Offset = &offset
	return ssq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ssq *SubscribeSchemaQuery) Unique(unique bool) *SubscribeSchemaQuery {
	ssq.ctx.Unique = &unique
	return ssq
}

// Order specifies how the records should be ordered.
func (ssq *SubscribeSchemaQuery) Order(o ...subscribeschema.OrderOption) *SubscribeSchemaQuery {
	ssq.order = append(ssq.order, o...)
	return ssq
}

// First returns the first SubscribeSchema entity from the query.
// Returns a *NotFoundError when no SubscribeSchema was found.
func (ssq *SubscribeSchemaQuery) First(ctx context.Context) (*SubscribeSchema, error) {
	nodes, err := ssq.Limit(1).All(setContextOp(ctx, ssq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscribeschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) FirstX(ctx context.Context) *SubscribeSchema {
	node, err := ssq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscribeSchema ID from the query.
// Returns a *NotFoundError when no SubscribeSchema ID was found.
func (ssq *SubscribeSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(1).IDs(setContextOp(ctx, ssq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscribeschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := ssq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscribeSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscribeSchema entity is found.
// Returns a *NotFoundError when no SubscribeSchema entities are found.
func (ssq *SubscribeSchemaQuery) Only(ctx context.Context) (*SubscribeSchema, error) {
	nodes, err := ssq.Limit(2).All(setContextOp(ctx, ssq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscribeschema.Label}
	default:
		return nil, &NotSingularError{subscribeschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) OnlyX(ctx context.Context) *SubscribeSchema {
	node, err := ssq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscribeSchema ID in the query.
// Returns a *NotSingularError when more than one SubscribeSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (ssq *SubscribeSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ssq.Limit(2).IDs(setContextOp(ctx, ssq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscribeschema.Label}
	default:
		err = &NotSingularError{subscribeschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := ssq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscribeSchemas.
func (ssq *SubscribeSchemaQuery) All(ctx context.Context) ([]*SubscribeSchema, error) {
	ctx = setContextOp(ctx, ssq.ctx, "All")
	if err := ssq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscribeSchema, *SubscribeSchemaQuery]()
	return withInterceptors[[]*SubscribeSchema](ctx, ssq, qr, ssq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) AllX(ctx context.Context) []*SubscribeSchema {
	nodes, err := ssq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscribeSchema IDs.
func (ssq *SubscribeSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ssq.ctx.Unique == nil && ssq.path != nil {
		ssq.Unique(true)
	}
	ctx = setContextOp(ctx, ssq.ctx, "IDs")
	if err = ssq.Select(subscribeschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := ssq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ssq *SubscribeSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Count")
	if err := ssq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ssq, querierCount[*SubscribeSchemaQuery](), ssq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) CountX(ctx context.Context) int {
	count, err := ssq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ssq *SubscribeSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ssq.ctx, "Exist")
	switch _, err := ssq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ssq *SubscribeSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := ssq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscribeSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ssq *SubscribeSchemaQuery) Clone() *SubscribeSchemaQuery {
	if ssq == nil {
		return nil
	}
	return &SubscribeSchemaQuery{
		config:     ssq.config,
		ctx:        ssq.ctx.Clone(),
		order:      append([]subscribeschema.OrderOption{}, ssq.order...),
		inters:     append([]Interceptor{}, ssq.inters...),
		predicates: append([]predicate.SubscribeSchema{}, ssq.predicates...),
		// clone intermediate query.
		sql:  ssq.sql.Clone(),
		path: ssq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (ssq *SubscribeSchemaQuery) GroupBy(field string, fields ...string) *SubscribeSchemaGroupBy {
	ssq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscribeSchemaGroupBy{build: ssq}
	grbuild.flds = &ssq.ctx.Fields
	grbuild.label = subscribeschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (ssq *SubscribeSchemaQuery) Select(fields ...string) *SubscribeSchemaSelect {
	ssq.ctx.Fields = append(ssq.ctx.Fields, fields...)
	sbuild := &SubscribeSchemaSelect{SubscribeSchemaQuery: ssq}
	sbuild.label = subscribeschema.Label
	sbuild.flds, sbuild.scan = &ssq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscribeSchemaSelect configured with the given aggregations.
func (ssq *SubscribeSchemaQuery) Aggregate(fns ...AggregateFunc) *SubscribeSchemaSelect {
	return ssq.Select().Aggregate(fns...)
}

func (ssq *SubscribeSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ssq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ssq); err != nil {
				return err
			}
		}
	}
	for _, f := range ssq.ctx.Fields {
		if !subscribeschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ssq.path != nil {
		prev, err := ssq.path(ctx)
		if err != nil {
			return err
		}
		ssq.sql = prev
	}
	return nil
}

func (ssq *SubscribeSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscribeSchema, error) {
	var (
		nodes = []*SubscribeSchema{}
		_spec = ssq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscribeSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscribeSchema{config: ssq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ssq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ssq *SubscribeSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ssq.querySpec()
	_spec.Node.Columns = ssq.ctx.Fields
	if len(ssq.ctx.Fields) > 0 {
		_spec.Unique = ssq.ctx.Unique != nil && *ssq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ssq.driver, _spec)
}

func (ssq *SubscribeSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscribeschema.Table, subscribeschema.Columns, sqlgraph.NewFieldSpec(subscribeschema.FieldID, field.TypeInt))
	_spec.From = ssq.sql
	if unique := ssq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ssq.path != nil {
		_spec.Unique = true
	}
	if fields := ssq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscribeschema.FieldID)
		for i := range fields {
			if fields[i] != subscribeschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ssq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ssq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ssq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ssq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ssq *SubscribeSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ssq.driver.Dialect())
	t1 := builder.Table(subscribeschema.Table)
	columns := ssq.ctx.Fields
	if len(columns) == 0 {
		columns = subscribeschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ssq.sql != nil {
		selector = ssq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ssq.ctx.Unique != nil && *ssq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ssq.predicates {
		p(selector)
	}
	for _, p := range ssq.order {
		p(selector)
	}
	if offset := ssq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ssq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubscribeSchemaGroupBy is the group-by builder for SubscribeSchema entities.
type SubscribeSchemaGroupBy struct {
	selector
	build *SubscribeSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ssgb *SubscribeSchemaGroupBy) Aggregate(fns ...AggregateFunc) *SubscribeSchemaGroupBy {
	ssgb.fns = append(ssgb.fns, fns...)
	return ssgb
}

// Scan applies the selector query and scans the result into the given value.
func (ssgb *SubscribeSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ssgb.build.ctx, "GroupBy")
	if err := ssgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscribeSchemaQuery, *SubscribeSchemaGroupBy](ctx, ssgb.build, ssgb, ssgb.build.inters, v)
}

func (ssgb *SubscribeSchemaGroupBy) sqlScan(ctx context.Context, root *SubscribeSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ssgb.fns))
	for _, fn := range ssgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ssgb.flds)+len(ssgb.fns))
		for _, f := range *ssgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ssgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ssgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscribeSchemaSelect is the builder for selecting fields of SubscribeSchema entities.
type SubscribeSchemaSelect struct {
	*SubscribeSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sss *SubscribeSchemaSelect) Aggregate(fns ...AggregateFunc) *SubscribeSchemaSelect {
	sss.fns = append(sss.fns, fns...)
	return sss
}

// Scan applies the selector query and scans the result into the given value.
func (sss *SubscribeSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sss.ctx, "Select")
	if err := sss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscribeSchemaQuery, *SubscribeSchemaSelect](ctx, sss.SubscribeSchemaQuery, sss, sss.inters, v)
}

func (sss *SubscribeSchemaSelect) sqlScan(ctx context.Context, root *SubscribeSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sss.fns))
	for _, fn := range sss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
