// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"persona/libs/database/ent/threadschema"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ThreadSchema is the model entity for the ThreadSchema schema.
type ThreadSchema struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ThreadSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case threadschema.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ThreadSchema fields.
func (ts *ThreadSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case threadschema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ts.ID = int(value.Int64)
		default:
			ts.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ThreadSchema.
// This includes values selected through modifiers, order, etc.
func (ts *ThreadSchema) Value(name string) (ent.Value, error) {
	return ts.selectValues.Get(name)
}

// Update returns a builder for updating this ThreadSchema.
// Note that you need to call ThreadSchema.Unwrap() before calling this method if this ThreadSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (ts *ThreadSchema) Update() *ThreadSchemaUpdateOne {
	return NewThreadSchemaClient(ts.config).UpdateOne(ts)
}

// Unwrap unwraps the ThreadSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ts *ThreadSchema) Unwrap() *ThreadSchema {
	_tx, ok := ts.config.driver.(*txDriver)
	if !ok {
		panic("ent: ThreadSchema is not a transactional entity")
	}
	ts.config.driver = _tx.drv
	return ts
}

// String implements the fmt.Stringer.
func (ts *ThreadSchema) String() string {
	var builder strings.Builder
	builder.WriteString("ThreadSchema(")
	builder.WriteString(fmt.Sprintf("id=%v", ts.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ThreadSchemas is a parsable slice of ThreadSchema.
type ThreadSchemas []*ThreadSchema
