// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"persona/libs/database/ent/predicate"
	"persona/libs/database/ent/threadschema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ThreadSchemaUpdate is the builder for updating ThreadSchema entities.
type ThreadSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *ThreadSchemaMutation
}

// Where appends a list predicates to the ThreadSchemaUpdate builder.
func (tsu *ThreadSchemaUpdate) Where(ps ...predicate.ThreadSchema) *ThreadSchemaUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// Mutation returns the ThreadSchemaMutation object of the builder.
func (tsu *ThreadSchemaUpdate) Mutation() *ThreadSchemaMutation {
	return tsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *ThreadSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *ThreadSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *ThreadSchemaUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *ThreadSchemaUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tsu *ThreadSchemaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(threadschema.Table, threadschema.Columns, sqlgraph.NewFieldSpec(threadschema.FieldID, field.TypeInt))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{threadschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// ThreadSchemaUpdateOne is the builder for updating a single ThreadSchema entity.
type ThreadSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ThreadSchemaMutation
}

// Mutation returns the ThreadSchemaMutation object of the builder.
func (tsuo *ThreadSchemaUpdateOne) Mutation() *ThreadSchemaMutation {
	return tsuo.mutation
}

// Where appends a list predicates to the ThreadSchemaUpdate builder.
func (tsuo *ThreadSchemaUpdateOne) Where(ps ...predicate.ThreadSchema) *ThreadSchemaUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *ThreadSchemaUpdateOne) Select(field string, fields ...string) *ThreadSchemaUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated ThreadSchema entity.
func (tsuo *ThreadSchemaUpdateOne) Save(ctx context.Context) (*ThreadSchema, error) {
	return withHooks(ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *ThreadSchemaUpdateOne) SaveX(ctx context.Context) *ThreadSchema {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *ThreadSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *ThreadSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tsuo *ThreadSchemaUpdateOne) sqlSave(ctx context.Context) (_node *ThreadSchema, err error) {
	_spec := sqlgraph.NewUpdateSpec(threadschema.Table, threadschema.Columns, sqlgraph.NewFieldSpec(threadschema.FieldID, field.TypeInt))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ThreadSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, threadschema.FieldID)
		for _, f := range fields {
			if !threadschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != threadschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ThreadSchema{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{threadschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
