// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"iam/libs/database/ent/userschema"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserSchema is the model entity for the UserSchema schema.
type UserSchema struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Email holds the value of the "email" field.
	Email        string `json:"email,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSchema) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userschema.FieldID:
			values[i] = new(sql.NullInt64)
		case userschema.FieldUsername, userschema.FieldPassword, userschema.FieldEmail:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSchema fields.
func (us *UserSchema) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userschema.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			us.ID = int(value.Int64)
		case userschema.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				us.Username = value.String
			}
		case userschema.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				us.Password = value.String
			}
		case userschema.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				us.Email = value.String
			}
		default:
			us.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSchema.
// This includes values selected through modifiers, order, etc.
func (us *UserSchema) Value(name string) (ent.Value, error) {
	return us.selectValues.Get(name)
}

// Update returns a builder for updating this UserSchema.
// Note that you need to call UserSchema.Unwrap() before calling this method if this UserSchema
// was returned from a transaction, and the transaction was committed or rolled back.
func (us *UserSchema) Update() *UserSchemaUpdateOne {
	return NewUserSchemaClient(us.config).UpdateOne(us)
}

// Unwrap unwraps the UserSchema entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (us *UserSchema) Unwrap() *UserSchema {
	_tx, ok := us.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSchema is not a transactional entity")
	}
	us.config.driver = _tx.drv
	return us
}

// String implements the fmt.Stringer.
func (us *UserSchema) String() string {
	var builder strings.Builder
	builder.WriteString("UserSchema(")
	builder.WriteString(fmt.Sprintf("id=%v, ", us.ID))
	builder.WriteString("username=")
	builder.WriteString(us.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(us.Password)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(us.Email)
	builder.WriteByte(')')
	return builder.String()
}

// UserSchemas is a parsable slice of UserSchema.
type UserSchemas []*UserSchema
