// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"iam/libs/database/ent/predicate"
	"iam/libs/database/ent/userschema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserSchemaDelete is the builder for deleting a UserSchema entity.
type UserSchemaDelete struct {
	config
	hooks    []Hook
	mutation *UserSchemaMutation
}

// Where appends a list predicates to the UserSchemaDelete builder.
func (usd *UserSchemaDelete) Where(ps ...predicate.UserSchema) *UserSchemaDelete {
	usd.mutation.Where(ps...)
	return usd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (usd *UserSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, usd.sqlExec, usd.mutation, usd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (usd *UserSchemaDelete) ExecX(ctx context.Context) int {
	n, err := usd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (usd *UserSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userschema.Table, sqlgraph.NewFieldSpec(userschema.FieldID, field.TypeInt))
	if ps := usd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, usd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	usd.mutation.done = true
	return affected, err
}

// UserSchemaDeleteOne is the builder for deleting a single UserSchema entity.
type UserSchemaDeleteOne struct {
	usd *UserSchemaDelete
}

// Where appends a list predicates to the UserSchemaDelete builder.
func (usdo *UserSchemaDeleteOne) Where(ps ...predicate.UserSchema) *UserSchemaDeleteOne {
	usdo.usd.mutation.Where(ps...)
	return usdo
}

// Exec executes the deletion query.
func (usdo *UserSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := usdo.usd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (usdo *UserSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := usdo.Exec(ctx); err != nil {
		panic(err)
	}
}
