// Code generated by ent, DO NOT EDIT.

package phoneschema

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the phoneschema type in the database.
	Label = "phone_schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the phoneschema in the database.
	Table = "Phone"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "Phone"
	// OwnerInverseTable is the table name for the ProfileSchema entity.
	// It exists in this package in order to avoid circular dependency with the "profileschema" package.
	OwnerInverseTable = "Profile"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "profile_schema_phone"
)

// Columns holds all SQL columns for phoneschema fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "Phone"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"profile_schema_phone",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PhoneSchema queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
	)
}
