// Code generated by ent, DO NOT EDIT.

package profileschema

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the profileschema type in the database.
	Label = "profile_schema"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgePhoto holds the string denoting the photo edge name in mutations.
	EdgePhoto = "photo"
	// EdgePhone holds the string denoting the phone edge name in mutations.
	EdgePhone = "phone"
	// Table holds the table name of the profileschema in the database.
	Table = "Profile"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "Profile"
	// OwnerInverseTable is the table name for the UserSchema entity.
	// It exists in this package in order to avoid circular dependency with the "userschema" package.
	OwnerInverseTable = "User"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_schema_profile"
	// PhotoTable is the table that holds the photo relation/edge.
	PhotoTable = "photo"
	// PhotoInverseTable is the table name for the PhotoSchema entity.
	// It exists in this package in order to avoid circular dependency with the "photoschema" package.
	PhotoInverseTable = "photo"
	// PhotoColumn is the table column denoting the photo relation/edge.
	PhotoColumn = "profile_schema_photo"
	// PhoneTable is the table that holds the phone relation/edge.
	PhoneTable = "Phone"
	// PhoneInverseTable is the table name for the PhoneSchema entity.
	// It exists in this package in order to avoid circular dependency with the "phoneschema" package.
	PhoneInverseTable = "Phone"
	// PhoneColumn is the table column denoting the phone relation/edge.
	PhoneColumn = "profile_schema_phone"
)

// Columns holds all SQL columns for profileschema fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "Profile"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_schema_profile",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ProfileSchema queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByPhotoField orders the results by photo field.
func ByPhotoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPhotoStep(), sql.OrderByField(field, opts...))
	}
}

// ByPhoneField orders the results by phone field.
func ByPhoneField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPhoneStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
	)
}
func newPhotoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhotoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PhotoTable, PhotoColumn),
	)
}
func newPhoneStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhoneInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PhoneTable, PhoneColumn),
	)
}
